import type { LessonDefinitionV2 } from '../types'

export const BRANCHING_LESSONS: LessonDefinitionV2[] = [
  {
    id: 'branches',
    title: 'Names, Pointers & Parallel Work',
    icon: '🌿',
    description: 'Create a branch, commit on it, and prove main stayed put',
    objective: 'Treat branches as movable refs and predict which ref moves when a commit is created.',
    category: 'branching',
    prerequisites: ['snapshot-transfer'],
    order: 0,
    scenario: 'branching/base',
    mode: 'guided',
    concepts: {
      requires: ['commit', 'branch', 'head'],
      introduces: ['branch-movement'],
      practices: ['status-orientation'],
      assesses: ['branch', 'head', 'branch-movement'],
    },
    phases: ['model', 'predict', 'act', 'inspect', 'explain', 'retrieve'],
    steps: [
      {
        id: 'branch-create',
        title: 'Create and Switch in One Step',
        description: 'Create feature and attach HEAD to it.',
        hint: 'Goal: create a new feature branch and switch to it without copying the project.',
        concept: 'A branch is a movable ref; `switch -c` creates a name at the current commit and attaches HEAD to it.',
        concepts: ['branch', 'head'],
        exactCommand: 'git switch -c feature',
        progressiveHints: [
          'Use the branch-focused switching command.',
          'Create-and-switch uses `switch -c`.',
          'Type: git switch -c feature',
        ],
        estimatedTime: 35,
        expectedOutcome: 'feature exists and HEAD is attached to feature; main still points at the base commit.',
        checkpointQuestions: ['Did creating the branch duplicate the commits?'],
        knowledgeCheck: {
          question: 'What did branch creation copy?',
          options: [
            'Nothing; it created another ref to the existing commit',
            'The entire repository directory',
            'Every commit into new objects',
          ],
          correctOption: 0,
          explanation: 'Creating a branch is cheap because it creates a new movable name.',
        },
        assessment: {
          pattern: '^git\\s+switch\\s+-c\\s+feature$',
          requiresPrediction: true,
          goal: [
            { type: 'branch-exists', branch: 'feature' },
            { type: 'head-branch', branch: 'feature' },
          ],
        },
      },
      {
        id: 'branch-list',
        title: 'Inspect the Names',
        description: 'List branches before creating divergent history.',
        hint: 'Goal: verify which branch HEAD is attached to.',
        concept: 'Branch listing is observation; the active branch is marked.',
        concepts: ['branch', 'head'],
        exactCommand: 'git branch',
        progressiveHints: [
          'Use the branch command without a name.',
          'List refs with `git branch`.',
          'Type: git branch',
        ],
        estimatedTime: 20,
        expectedOutcome: 'main and feature are listed and feature is current.',
        checkpointQuestions: ['Which ref will the next commit advance?'],
        knowledgeCheck: {
          question: 'If you commit now, which branch moves?',
          options: ['feature only', 'main only', 'both'],
          correctOption: 0,
          explanation: 'HEAD is attached to feature, so feature receives the new commit.',
        },
        assessment: {
          pattern: '^git\\s+branch$',
          requiresPrediction: true,
          goal: [{ type: 'head-branch', branch: 'feature' }],
        },
      },
      {
        id: 'checkout',
        title: 'Make Feature Work Visible',
        description: 'Change README.md while HEAD is on feature.',
        hint: 'Goal: create a working-tree change on the active feature branch.',
        concept:
          'Working edits are not branch-specific until recorded, but the current branch determines which ref a later commit advances.',
        concepts: ['working-tree', 'head'],
        exactCommand: 'edit README.md Feature-work',
        progressiveHints: ['Use the sandbox editor.', 'Edit README.md.', 'Type: edit README.md Feature-work'],
        estimatedTime: 20,
        expectedOutcome: 'Only the working tree changes.',
        checkpointQuestions: ['Has main moved yet?'],
        knowledgeCheck: {
          question: 'Has either branch moved just because you edited a file?',
          options: ['No', 'Yes, feature moved immediately'],
          correctOption: 0,
          explanation: 'Refs move on recorded history operations such as commit, not on ordinary file edits.',
        },
        assessment: { pattern: '^edit\\s+README\\.md\\s+.+$', requiresPrediction: true },
      },
      {
        id: 'branch-stage',
        title: 'Select Feature Content',
        description: 'Stage the feature edit.',
        hint: 'Goal: put README.md in the candidate snapshot.',
        concept: 'Staging still selects content exactly as it did on main.',
        concepts: ['staging-area', 'selective-staging'],
        exactCommand: 'git add README.md',
        progressiveHints: [
          'Use the same selective staging operation.',
          'Stage README.md only.',
          'Type: git add README.md',
        ],
        estimatedTime: 20,
        expectedOutcome: 'README.md is staged.',
        checkpointQuestions: ['Did staging move a branch?'],
        knowledgeCheck: {
          question: 'Which layer changed?',
          options: ['Index/staging area', 'main ref', 'remote branch'],
          correctOption: 0,
          explanation: 'Add changes the index, not history refs.',
        },
        assessment: {
          pattern: '^git\\s+add\\s+README\\.md$',
          requiresPrediction: true,
          goal: [{ type: 'staged-includes', path: 'README.md' }],
        },
      },
      {
        id: 'commit-branch',
        title: 'Advance Feature Only',
        description: 'Commit the feature change.',
        hint: 'Goal: create a commit while HEAD remains on feature.',
        concept: 'Committing advances the current branch ref and leaves main unchanged.',
        concepts: ['commit', 'branch-movement'],
        exactCommand: 'git commit -m "Feature work"',
        progressiveHints: ['Record the index.', 'Commit with a message.', 'Type: git commit -m "Feature work"'],
        estimatedTime: 30,
        expectedOutcome: 'A new commit is created and feature advances to it.',
        checkpointQuestions: ['Which ref moved?'],
        knowledgeCheck: {
          question: 'Where is main after this feature commit?',
          options: ['Still at the base commit', 'Automatically advanced with feature'],
          correctOption: 0,
          explanation: 'Only the currently checked-out branch advances.',
        },
        assessment: {
          pattern: '^git\\s+commit\\s+-m\\s+".+"$',
          requiresPrediction: true,
          goal: [
            { type: 'head-branch', branch: 'feature' },
            { type: 'commit-count-at-least', count: 2 },
          ],
        },
      },
      {
        id: 'checkout-main',
        title: 'Return to Main',
        description: 'Switch HEAD back to main and observe the working tree return to main’s snapshot.',
        hint: 'Goal: attach HEAD to main.',
        concept: 'Switching changes HEAD attachment and updates visible files to the selected commit.',
        concepts: ['head', 'branch'],
        exactCommand: 'git switch main',
        progressiveHints: ['Use the branch-focused switching command.', 'Switch to main.', 'Type: git switch main'],
        estimatedTime: 25,
        expectedOutcome: 'HEAD is on main while feature remains safely ahead on its own commit.',
        checkpointQuestions: ['Where did the feature commit go?'],
        knowledgeCheck: {
          question: 'Did switching back delete the feature commit?',
          options: ['No; feature still names it', 'Yes; only the current branch exists'],
          correctOption: 0,
          explanation: 'Switching changes current location; it does not erase the other branch/ref.',
        },
        assessment: {
          pattern: '^git\\s+switch\\s+main$',
          requiresPrediction: true,
          goal: [{ type: 'head-branch', branch: 'main' }],
        },
      },
    ],
  },
  {
    id: 'merging',
    title: 'Merge Case 1: Fast-Forward',
    icon: '⏩',
    description: 'See a merge that needs no merge commit at all',
    objective: 'Recognize when main can simply move forward to an existing descendant commit.',
    category: 'merging',
    prerequisites: ['branches'],
    order: 0,
    scenario: 'merge/fast-forward',
    mode: 'guided',
    concepts: {
      requires: ['branch-movement'],
      introduces: ['fast-forward'],
      practices: ['status-orientation'],
      assesses: ['fast-forward'],
    },
    phases: ['model', 'predict', 'act', 'inspect', 'explain', 'retrieve'],
    steps: [
      {
        id: 'merge-branch',
        title: 'Fast-Forward Main',
        description: 'feature is strictly ahead of main. Integrate it.',
        hint: 'Goal: bring feature into main and predict whether a new commit object is necessary.',
        concept: 'If main is an ancestor of feature, merge can advance main directly.',
        concepts: ['fast-forward', 'branch-movement'],
        exactCommand: 'git merge feature',
        progressiveHints: [
          'Use merge while on the receiving branch.',
          'Merge feature into main.',
          'Type: git merge feature',
        ],
        estimatedTime: 35,
        expectedOutcome: 'main moves to feature’s existing tip; no two-parent merge commit is created.',
        checkpointQuestions: ['Why was no new merge commit necessary?'],
        knowledgeCheck: {
          question: 'What distinguishes this fast-forward?',
          options: [
            'The receiving ref moves to an existing descendant commit',
            'Git always creates a two-parent commit',
            'Both branches are deleted',
          ],
          correctOption: 0,
          explanation: 'There is no divergent main history to join, so ref movement is sufficient.',
        },
        assessment: {
          pattern: '^git\\s+merge\\s+feature$',
          requiresPrediction: true,
          goal: [{ type: 'head-branch', branch: 'main' }],
        },
      },
      {
        id: 'merge-log',
        title: 'Inspect the Linear Result',
        description: 'Read history after the fast-forward.',
        hint: 'Goal: confirm there is still a linear parent chain.',
        concept: 'Topology is evidence: fast-forward produces no new join node.',
        concepts: ['fast-forward'],
        exactCommand: 'git log',
        progressiveHints: ['Inspect history.', 'Use log.', 'Type: git log'],
        estimatedTime: 20,
        expectedOutcome: 'History is readable without a new merge node.',
        checkpointQuestions: ['How would a true merge look different?'],
        knowledgeCheck: {
          question: 'How many parents should the current feature commit have?',
          options: ['One parent in this simple history', 'Two because merge was typed'],
          correctOption: 0,
          explanation: 'The command was merge, but the topology allowed a fast-forward rather than a merge commit.',
        },
        assessment: { pattern: '^git\\s+log$', requiresPrediction: true },
      },
    ],
  },
  {
    id: 'merge-commit-lab',
    title: 'Merge Case 2: Diverged Histories',
    icon: '🔀',
    description: 'Create a real two-parent merge commit',
    objective: 'Distinguish a true history join from a fast-forward by its parent topology.',
    category: 'merging',
    prerequisites: ['merging'],
    order: 1,
    scenario: 'merge/diverged',
    mode: 'practice',
    concepts: {
      requires: ['fast-forward', 'branch-movement'],
      introduces: ['merge-commit'],
      practices: ['status-orientation'],
      assesses: ['merge-commit', 'transfer-practice'],
    },
    phases: ['predict', 'act', 'inspect', 'explain', 'transfer'],
    steps: [
      {
        id: 'merge-diverged',
        title: 'Join the Diverged Lines',
        description: 'main and feature both have unique commits on different files. Integrate feature into main.',
        hint: 'Goal: preserve both ancestries in the resulting history.',
        concept: 'Diverged histories require a join commit when a normal merge is used.',
        concepts: ['merge-commit', 'transfer-practice'],
        exactCommand: 'git merge feature',
        progressiveHints: [
          'Use the integration operation from the receiving main branch.',
          'Merge feature.',
          'Type: git merge feature',
        ],
        estimatedTime: 40,
        expectedOutcome: 'A new merge commit with two parents is created on main.',
        checkpointQuestions: ['What do the two parent links mean?'],
        knowledgeCheck: {
          question: 'Why does this case create a new merge commit?',
          options: [
            'Both branches have unique ancestry that must be joined',
            'Every merge command always does',
            'Because feature has a longer name',
          ],
          correctOption: 0,
          explanation: 'The branches diverged after their common base.',
        },
        assessment: {
          pattern: '^git\\s+merge\\s+feature$',
          requiresPrediction: true,
          goal: [{ type: 'head-parent-count', count: 2 }],
        },
      },
    ],
  },
  {
    id: 'merge-conflicts',
    title: 'Merge Case 3: Conflict & Recovery',
    icon: '🧯',
    description: 'Safely inspect, abort, reproduce, and resolve a merge conflict',
    objective:
      'Treat a conflict as an explicit paused operation with inspectable files, an abort path, and a resolution path.',
    category: 'merging',
    prerequisites: ['merge-commit-lab'],
    order: 2,
    scenario: 'merge/conflict',
    mode: 'recovery',
    concepts: {
      requires: ['merge-commit'],
      introduces: ['merge-conflict'],
      practices: ['recovery', 'status-orientation'],
      assesses: ['merge-conflict', 'recovery'],
    },
    phases: ['predict', 'act', 'inspect', 'explain', 'retrieve', 'transfer'],
    steps: [
      {
        id: 'conflict-start',
        title: 'Let Git Stop Safely',
        description: 'Both branches changed README.md differently. Attempt the merge and expect Git to stop.',
        hint: 'Goal: observe the conflict state; a non-zero result is expected evidence here.',
        concept: 'A conflict is a paused merge, not a destroyed repository.',
        concepts: ['merge-conflict'],
        exactCommand: 'git merge feature',
        progressiveHints: [
          'Attempt normal integration.',
          'Merge feature into current main.',
          'Type: git merge feature',
        ],
        estimatedTime: 35,
        expectedOutcome: 'Git reports a content conflict, writes conflict markers, and records an in-progress merge.',
        checkpointQuestions: ['Why is this failure still useful state?'],
        knowledgeCheck: {
          question: 'What does the merge error mean here?',
          options: [
            'Git paused for a human decision; both versions are still inspectable',
            'All history was deleted',
            'The remote is unavailable',
          ],
          correctOption: 0,
          explanation: 'Conflict resolution is an explicit integration state.',
        },
        assessment: {
          pattern: '^git\\s+merge\\s+feature$',
          requiresPrediction: true,
          expectedResult: 'failure',
          goal: [{ type: 'pending-operation', operation: 'merge' }],
        },
      },
      {
        id: 'conflict-abort',
        title: 'Exercise the Escape Hatch',
        description: 'Abort the conflicted merge and restore the pre-merge state.',
        hint: 'Goal: return to the exact pre-merge branch/worktree state.',
        concept: 'Abort is a first-class recovery path when you are not ready to resolve.',
        concepts: ['merge-conflict', 'recovery'],
        exactCommand: 'git merge --abort',
        progressiveHints: ['Use merge’s abort mode.', 'The flag is `--abort`.', 'Type: git merge --abort'],
        estimatedTime: 25,
        expectedOutcome: 'The pending operation disappears and the pre-merge working tree is restored.',
        checkpointQuestions: ['Why is abort useful before experimenting further?'],
        knowledgeCheck: {
          question: 'What should abort preserve?',
          options: [
            'The pre-merge commit history and working state',
            'Conflict markers forever',
            'A partial merge commit',
          ],
          correctOption: 0,
          explanation: 'Abort intentionally returns to the pre-operation state.',
        },
        assessment: {
          pattern: '^git\\s+merge\\s+--abort$',
          requiresPrediction: true,
          goal: [{ type: 'no-pending-operation' }],
        },
      },
      {
        id: 'conflict-repeat',
        title: 'Reproduce the Conflict',
        description: 'Run the same merge again so you can resolve it deliberately.',
        hint: 'Goal: recreate the safe paused state.',
        concept: 'Deterministic labs make productive error practice repeatable.',
        concepts: ['merge-conflict', 'recovery'],
        exactCommand: 'git merge feature',
        progressiveHints: ['Repeat the integration attempt.', 'Merge feature.', 'Type: git merge feature'],
        estimatedTime: 20,
        expectedOutcome: 'The same README conflict is reproduced.',
        checkpointQuestions: ['Why is reproducibility valuable for recovery training?'],
        knowledgeCheck: {
          question: 'Is reproducing this conflict dangerous in the lab?',
          options: [
            'No; the scenario is resettable and the operation has an abort path',
            'Yes; conflicts permanently corrupt Git',
          ],
          correctOption: 0,
          explanation: 'The lab deliberately makes this failure safe to inspect.',
        },
        assessment: {
          pattern: '^git\\s+merge\\s+feature$',
          requiresPrediction: true,
          expectedResult: 'failure',
          goal: [{ type: 'pending-operation', operation: 'merge' }],
        },
      },
      {
        id: 'conflict-edit',
        title: 'Choose the Resolved Content',
        description: 'Replace conflict markers with one deliberate README.md resolution.',
        hint: 'Goal: make README.md contain your chosen final content.',
        concept: 'Humans resolve semantic intent; Git only identifies the overlapping change.',
        concepts: ['merge-conflict'],
        exactCommand: 'edit README.md Resolved-README',
        progressiveHints: [
          'Use the sandbox editor on the conflicted path.',
          'Replace the marker content with a coherent final version.',
          'Type: edit README.md Resolved-README',
        ],
        estimatedTime: 35,
        expectedOutcome: 'README.md contains a deliberate resolution but the merge is still pending.',
        checkpointQuestions: ['Why is editing alone not enough?'],
        knowledgeCheck: {
          question: 'What tells Git the conflict path is resolved?',
          options: ['Stage the resolved path after editing', 'Merely close the file', 'Run fetch'],
          correctOption: 0,
          explanation: 'Staging the resolved content records the resolution for merge completion.',
        },
        assessment: {
          pattern: '^edit\\s+README\\.md\\s+.+$',
          requiresPrediction: true,
          goal: [{ type: 'pending-operation', operation: 'merge' }],
        },
      },
      {
        id: 'conflict-stage',
        title: 'Mark the Resolution',
        description: 'Stage the resolved README.md.',
        hint: 'Goal: select the resolved content into the index.',
        concept: 'During conflict resolution, add marks the selected path resolved for the pending operation.',
        concepts: ['merge-conflict', 'staging-area'],
        exactCommand: 'git add README.md',
        progressiveHints: [
          'Use the normal staging operation on the resolved path.',
          'Stage README.md.',
          'Type: git add README.md',
        ],
        estimatedTime: 20,
        expectedOutcome: 'The resolved README.md is staged while the merge remains pending.',
        checkpointQuestions: ['What does the index now represent?'],
        knowledgeCheck: {
          question: 'What is the index holding now?',
          options: [
            'The chosen merge result for README.md',
            'Both unedited conflict versions automatically',
            'A remote ref',
          ],
          correctOption: 0,
          explanation: 'The staged content is the candidate result for the merge commit.',
        },
        assessment: {
          pattern: '^git\\s+add\\s+README\\.md$',
          requiresPrediction: true,
          goal: [
            { type: 'staged-includes', path: 'README.md' },
            { type: 'pending-operation', operation: 'merge' },
          ],
        },
      },
      {
        id: 'conflict-commit',
        title: 'Complete the Merge',
        description: 'Record the resolved merge commit.',
        hint: 'Goal: finish the pending operation and preserve both parent histories.',
        concept: 'A resolved normal merge completes as a two-parent commit.',
        concepts: ['merge-conflict', 'merge-commit'],
        exactCommand: 'git commit -m "Resolve README conflict"',
        progressiveHints: [
          'Record the resolved index.',
          'Commit the merge result.',
          'Type: git commit -m "Resolve README conflict"',
        ],
        estimatedTime: 30,
        expectedOutcome: 'The pending merge clears and main points at a two-parent resolved merge commit.',
        checkpointQuestions: ['How can topology prove both histories were preserved?'],
        knowledgeCheck: {
          question: 'How many parents should the resolved merge commit have?',
          options: ['Two', 'Zero', 'Exactly three'],
          correctOption: 0,
          explanation: 'The merge join records both prior branch tips as parents.',
        },
        assessment: {
          pattern: '^git\\s+commit\\s+-m\\s+".+"$',
          requiresPrediction: true,
          goal: [{ type: 'head-parent-count', count: 2 }, { type: 'no-pending-operation' }],
        },
      },
    ],
  },
  {
    id: 'rebase',
    title: 'Rebase: Replay, Don’t Move Commits',
    icon: '♻️',
    description: 'Replay feature changes onto a newer main while preserving main’s independent work',
    objective: 'Explain rebase as creation of replacement commits with new IDs, not movement of immutable commits.',
    category: 'merging',
    prerequisites: ['merge-conflicts'],
    order: 3,
    scenario: 'rebase/diverged',
    mode: 'guided',
    concepts: {
      requires: ['branch-movement', 'merge-commit'],
      introduces: ['rebase-replay'],
      practices: ['status-orientation'],
      assesses: ['rebase-replay'],
    },
    phases: ['model', 'predict', 'act', 'inspect', 'explain', 'retrieve'],
    steps: [
      {
        id: 'rebase-start',
        title: 'Inspect the Divergence',
        description: 'feature and main both have unique work; HEAD is on feature.',
        hint: 'Goal: orient before rewriting feature history.',
        concept: 'Rebase is safest when you understand both the receiving base and commits to replay.',
        concepts: ['rebase-replay', 'status-orientation'],
        exactCommand: 'git log',
        progressiveHints: ['Use a history observation command first.', 'Inspect with log.', 'Type: git log'],
        estimatedTime: 25,
        expectedOutcome: 'History is displayed without mutation before the rewrite.',
        checkpointQuestions: ['Which branch’s commits will be replaced?'],
        knowledgeCheck: {
          question: 'Which commits are candidates for replacement?',
          options: ['feature’s commits after the common base', 'All commits on main', 'Remote commits only'],
          correctOption: 0,
          explanation: 'Rebase replays the current branch’s unique commits onto the target base.',
        },
        assessment: {
          pattern: '^git\\s+log$',
          requiresPrediction: true,
          goal: [{ type: 'head-branch', branch: 'feature' }],
        },
      },
      {
        id: 'rebase-exec',
        title: 'Replay Feature onto Main',
        description: 'Rebase feature onto main.',
        hint: 'Goal: preserve feature’s change while making main the new base.',
        concept: 'The feature change is replayed into a replacement commit with a new ID.',
        concepts: ['rebase-replay'],
        exactCommand: 'git rebase main',
        progressiveHints: [
          'Use the history-replay operation.',
          'Target main as the new base.',
          'Type: git rebase main',
        ],
        estimatedTime: 40,
        safetyNote:
          'Rebase rewrites commit IDs. Do not casually rebase shared commits that collaborators already pulled.',
        expectedOutcome:
          'feature points to replacement commit(s) on top of main while main’s independent README change remains present.',
        checkpointQuestions: ['Why must the rebased commit have a new ID?'],
        knowledgeCheck: {
          question: 'What happened to feature’s old commit object?',
          options: [
            'Its change was replayed into a new commit ID',
            'The immutable commit was physically moved',
            'Main was discarded',
          ],
          correctOption: 0,
          explanation: 'Commit identity includes ancestry, so changing the parent creates a different commit.',
        },
        assessment: {
          pattern: '^git\\s+rebase\\s+main$',
          requiresPrediction: true,
          goal: [{ type: 'head-branch', branch: 'feature' }],
        },
      },
    ],
  },
]
