import type { LessonDefinitionV2 } from '../types'

export const CORE_LESSONS: LessonDefinitionV2[] = [
  {
    id: 'orientation',
    title: 'Git Orientation',
    icon: '🧭',
    description: 'Build the mental model before memorizing command syntax',
    objective:
      'Distinguish visible files, the index, immutable commits, branch refs, and HEAD before using Git commands.',
    category: 'basics',
    prerequisites: [],
    order: -10,
    scenario: 'orientation/empty',
    mode: 'guided',
    concepts: {
      requires: [],
      introduces: ['version-control', 'repository', 'working-tree', 'staging-area', 'commit', 'branch', 'head'],
      practices: [],
      assesses: ['repository', 'staging-area', 'branch', 'head'],
    },
    phases: ['model', 'retrieve'],
    steps: [
      {
        id: 'why-git',
        title: 'Why Git Exists',
        description:
          'Git records meaningful project states so change can be compared, shared, and recovered without copied “final-final” folders.',
        hint: 'Think about the human problem first; no command is needed.',
        concept: 'Version control is a project memory system, not a collection of magic terminal incantations.',
        concepts: ['version-control'],
        expectedOutcome: 'You can state why recorded history is more useful than manually copied project folders.',
        checkpointQuestions: ['What problem does version control solve?'],
        knowledgeCheck: {
          question: 'What is Git primarily giving a project?',
          options: [
            'A recorded, comparable history of project states',
            'A faster text editor',
            'Automatic cloud backup of every file',
          ],
          correctOption: 0,
          explanation:
            'Git is fundamentally a version-control/history system; hosting and editors are separate concerns.',
        },
      },
      {
        id: 'repo-anatomy',
        title: 'Repository Anatomy',
        description:
          'A repository combines visible project files with hidden Git metadata that records history, refs, configuration, and index state.',
        hint: 'Separate what you edit as project content from what Git maintains as metadata.',
        concept: 'The project tree and the .git database are different kinds of state.',
        concepts: ['repository', 'working-tree'],
        expectedOutcome: 'You can distinguish project files from .git metadata.',
        checkpointQuestions: ['Which part do you normally edit directly?'],
        knowledgeCheck: {
          question: 'Which statement is safest for a beginner?',
          options: [
            'Edit project files; let Git manage .git metadata',
            'Edit .git objects by hand for normal commits',
            '.git is just a cache and can always be deleted',
          ],
          correctOption: 0,
          explanation:
            'Normal Git work changes project files through Git commands; hand-editing .git internals is not the beginner workflow.',
        },
      },
      {
        id: 'three-areas',
        title: 'Working Tree, Staging Area, Commit',
        description:
          'Visible files can differ from the index, and the index can differ from the already recorded commit.',
        hint: 'Think “working content → selected next snapshot → recorded history”.',
        concept: 'The staging area is a deliberate candidate snapshot, not a place files are physically moved into.',
        concepts: ['working-tree', 'staging-area'],
        expectedOutcome: 'You can identify the working tree, index, and commit as separate states.',
        checkpointQuestions: ['Why stage only one path when several files changed?'],
        knowledgeCheck: {
          question: 'After `git add README.md`, where is README.md?',
          options: [
            'Still in the working tree, with selected content also represented in the index',
            'Moved out of the working tree into Git history',
            'Already committed permanently',
          ],
          correctOption: 0,
          explanation:
            'Add selects/copies content into the index; the working file remains present and can diverge again.',
        },
      },
      {
        id: 'commit-model',
        title: 'Commits Are Linked Snapshots',
        description:
          'A commit records a project snapshot and parent relationship; branches are movable names pointing into that graph.',
        hint: 'Separate immutable commit identity from movable branch names.',
        concept: 'Commits stay fixed; refs move.',
        concepts: ['commit', 'branch', 'head'],
        expectedOutcome: 'You can explain a branch as a movable pointer rather than a copied directory.',
        checkpointQuestions: ['What moves when you commit on a branch?'],
        knowledgeCheck: {
          question: 'What normally moves after a new commit on `main`?',
          options: [
            'The `main` branch ref advances to the new commit',
            'Every old commit is rewritten',
            'All branch names advance together',
          ],
          correctOption: 0,
          explanation:
            'The new commit is created and the current branch ref advances; other refs stay where they were.',
        },
      },
      {
        id: 'safe-practice-loop',
        title: 'Safe Practice Loop',
        description: 'Orient, predict, act, inspect, and explain rather than relying on command memory alone.',
        hint: 'Observation is normal expert work, not temporary training wheels.',
        concept: 'A reliable Git loop repeatedly checks evidence before and after change.',
        concepts: ['status-orientation'],
        expectedOutcome: 'You have a repeatable way to approach unfamiliar Git states.',
        checkpointQuestions: ['What should happen before a destructive operation?'],
        knowledgeCheck: {
          question: 'Which sequence best matches the course method?',
          options: [
            'Orient → predict → act → inspect → explain',
            'Act repeatedly → read errors later',
            'Memorize commands → avoid status',
          ],
          correctOption: 0,
          explanation: 'The course uses prediction and evidence so syntax stays connected to repository state.',
        },
      },
    ],
  },
  {
    id: 'git-glossary',
    title: 'Git Glossary',
    icon: '📚',
    description: 'Retrieve the vocabulary used by the rest of the course',
    objective: 'Recognize the core state words before commands start combining them.',
    category: 'basics',
    prerequisites: ['orientation'],
    order: -9,
    scenario: 'orientation/empty',
    mode: 'guided',
    concepts: {
      requires: ['repository'],
      introduces: [],
      practices: ['working-tree', 'staging-area', 'commit', 'branch', 'head'],
      assesses: ['head'],
    },
    phases: ['retrieve'],
    steps: [
      {
        id: 'glossary-core',
        title: 'Core Vocabulary',
        description:
          'Repository, working tree, index, commit, branch, HEAD, remote, fetch, merge, and rebase each name a distinct mechanism.',
        hint: 'Use the Help panel as reference after attempting the retrieval question.',
        concept: 'Precise vocabulary reduces “Git magic” by giving states and relationships names.',
        concepts: ['repository', 'working-tree', 'staging-area', 'commit', 'branch', 'head'],
        expectedOutcome: 'You can distinguish location (`HEAD`) from a movable branch name and immutable commit.',
        checkpointQuestions: ['What names your current position?'],
        knowledgeCheck: {
          question: 'Which term represents where you currently are in Git history?',
          options: ['HEAD', 'origin', 'index'],
          correctOption: 0,
          explanation: 'HEAD identifies the current position, usually by being attached to a branch ref.',
        },
      },
    ],
  },
  {
    id: 'basics',
    title: 'Local Snapshots',
    icon: '🌱',
    description: 'Create and inspect focused local snapshots',
    objective: 'Explain and operate the working tree → index → commit loop with selective staging and inspection.',
    category: 'basics',
    prerequisites: ['orientation'],
    order: 0,
    scenario: 'local/default-uninitialized',
    mode: 'guided',
    concepts: {
      requires: ['repository', 'working-tree', 'staging-area', 'commit'],
      introduces: ['selective-staging', 'diff-inspection'],
      practices: ['status-orientation'],
      assesses: ['staging-area', 'selective-staging', 'commit', 'diff-inspection'],
    },
    phases: ['model', 'predict', 'act', 'inspect', 'explain', 'retrieve'],
    steps: [
      {
        id: 'init',
        title: 'Initialize a Repository',
        description: 'Create Git metadata for the current project folder.',
        hint: 'Goal: make this folder a repository without recording a commit yet.',
        concept: 'Initialization creates .git metadata and the initial branch/HEAD relationship.',
        concepts: ['repository', 'head'],
        exactCommand: 'git init',
        progressiveHints: ['Which Git action starts a repository?', 'Use the `init` subcommand.', 'Type: git init'],
        estimatedTime: 30,
        expectedOutcome:
          'The hidden .git repository metadata exists; the main branch/HEAD relationship exists and no commit exists yet.',
        checkpointQuestions: ['What did init create, and what did it not record?'],
        knowledgeCheck: {
          question: 'Did `git init` create the first commit?',
          options: ['No — it created repository metadata and refs only', 'Yes — every init creates a commit'],
          correctOption: 0,
          explanation: 'A commit requires selected content and an explicit commit action.',
        },
        assessment: { pattern: '^git\\s+init$', requiresPrediction: true, goal: [{ type: 'repository-initialized' }] },
      },
      {
        id: 'status1',
        title: 'Orient Before Recording',
        description: 'Inspect working and staged state without changing it.',
        hint: 'Goal: ask Git what is currently untracked, modified, or staged.',
        concept: 'Observation commands are a normal part of expert operation.',
        concepts: ['status-orientation'],
        exactCommand: 'git status',
        progressiveHints: ['Use an observation command.', 'The subcommand is `status`.', 'Type: git status'],
        estimatedTime: 25,
        expectedOutcome: 'Git reports repository state without a semantic state mutation.',
        checkpointQuestions: ['Which layer changed?'],
        knowledgeCheck: {
          question: 'What should `git status` change?',
          options: ['Nothing; it reports state', 'The index', 'The current branch ref'],
          correctOption: 0,
          explanation: 'Status is observational.',
        },
        assessment: { pattern: '^git\\s+status$', requiresPrediction: true },
      },
      {
        id: 'add1',
        title: 'Select One File',
        description: 'Stage only README.md instead of staging the whole project.',
        hint: 'Goal: select README.md for the first snapshot while leaving other paths outside the index.',
        concept: 'Selective staging controls snapshot boundaries.',
        concepts: ['staging-area', 'selective-staging'],
        exactCommand: 'git add README.md',
        progressiveHints: [
          'Choose the staging operation and name one path.',
          'Use `git add` with README.md rather than `.`.',
          'Type: git add README.md',
        ],
        estimatedTime: 35,
        expectedOutcome: 'README.md is represented in the index while other recipe paths remain unstaged/untracked.',
        checkpointQuestions: ['Why is a path-specific add safer for a focused commit?'],
        knowledgeCheck: {
          question: 'What did `git add README.md` select?',
          options: ['The current README.md content for the next snapshot', 'Every changed file', 'A new branch'],
          correctOption: 0,
          explanation: 'Add selects content into the index.',
        },
        assessment: {
          pattern: '^git\\s+add\\s+README\\.md$',
          requiresPrediction: true,
          goal: [
            { type: 'staged-includes', path: 'README.md' },
            { type: 'staged-excludes', path: 'recipes/pasta.md' },
          ],
        },
      },
      {
        id: 'staged-diff',
        title: 'Inspect the Candidate Snapshot',
        description: 'Compare the index with HEAD before committing.',
        hint: 'Goal: inspect what is staged, not what remains only in the working tree.',
        concept: '`git diff --staged` compares index content with the current commit.',
        concepts: ['diff-inspection', 'staging-area'],
        exactCommand: 'git diff --staged',
        progressiveHints: [
          'Use the diff view for staged content.',
          'Add the `--staged` flag to `git diff`.',
          'Type: git diff --staged',
        ],
        estimatedTime: 30,
        expectedOutcome: 'The README candidate snapshot is shown without state mutation.',
        checkpointQuestions: ['Which two states are being compared?'],
        knowledgeCheck: {
          question: 'What does `git diff --staged` compare?',
          options: ['Index vs HEAD', 'Working tree vs index', 'Two remotes'],
          correctOption: 0,
          explanation: 'The staged diff previews the candidate snapshot relative to the current commit.',
        },
        assessment: { pattern: '^git\\s+diff\\s+--(staged|cached)$', requiresPrediction: true },
      },
      {
        id: 'commit1',
        title: 'Record the Selected Snapshot',
        description: 'Create the first commit from exactly the staged content.',
        hint: 'Goal: turn the index selection into immutable history with a useful message.',
        concept: 'Commit creates an object and advances the current branch ref.',
        concepts: ['commit', 'branch-movement'],
        exactCommand: 'git commit -m "Record README"',
        progressiveHints: [
          'Use the operation that records the index.',
          'Use `git commit -m` with a message.',
          'Type: git commit -m "Record README"',
        ],
        estimatedTime: 40,
        expectedOutcome: 'A commit is created, main advances to it, and the sparse staging area is cleared.',
        checkpointQuestions: ['Which object was created and which ref moved?'],
        knowledgeCheck: {
          question: 'Which state does commit record?',
          options: [
            'The selected index content',
            'Every current working-tree edit automatically',
            'Only the command history',
          ],
          correctOption: 0,
          explanation: 'Commit records the index/candidate snapshot.',
        },
        assessment: {
          pattern: '^git\\s+commit\\s+-m\\s+".+"$',
          requiresPrediction: true,
          goal: [{ type: 'commit-count-at-least', count: 1 }],
        },
      },
      {
        id: 'edit-after-commit',
        title: 'Change the Working File Again',
        description: 'Create a working-tree change after the commit so the three states diverge again.',
        hint: 'Goal: edit README.md without staging it.',
        concept: 'A working file can diverge immediately after a commit; history does not change automatically.',
        concepts: ['working-tree'],
        exactCommand: 'edit README.md Second-version',
        progressiveHints: [
          'Use the sandbox file-edit command.',
          'Name README.md and new content.',
          'Type: edit README.md Second-version',
        ],
        estimatedTime: 20,
        expectedOutcome: 'Only working-tree content changes.',
        checkpointQuestions: ['Did history move?'],
        knowledgeCheck: {
          question: 'After editing but before add, where does the change exist?',
          options: ['Working tree only', 'Commit history only', 'Remote only'],
          correctOption: 0,
          explanation: 'An edit is not staged or committed automatically.',
        },
        assessment: { pattern: '^edit\\s+README\\.md\\s+.+$', requiresPrediction: true },
      },
      {
        id: 'working-diff',
        title: 'Inspect the Unstaged Difference',
        description: 'Compare working-tree README.md with the index.',
        hint: 'Goal: inspect the edit that has not been staged yet.',
        concept: 'Plain `git diff` compares the working tree with the index.',
        concepts: ['diff-inspection', 'working-tree'],
        exactCommand: 'git diff',
        progressiveHints: [
          'Use the observation command for unstaged content.',
          'Plain `git diff` is enough.',
          'Type: git diff',
        ],
        estimatedTime: 25,
        expectedOutcome: 'The README working-tree difference is shown without state mutation.',
        checkpointQuestions: ['Why is this different from --staged?'],
        knowledgeCheck: {
          question: 'What does plain `git diff` show here?',
          options: ['Working tree vs index', 'Index vs HEAD', 'Remote vs local'],
          correctOption: 0,
          explanation: 'Plain diff focuses on unstaged content.',
        },
        assessment: { pattern: '^git\\s+diff$', requiresPrediction: true },
      },
      {
        id: 'add2',
        title: 'Refresh the Index Selection',
        description: 'Stage the new README.md content.',
        hint: 'Goal: update the index entry for README.md.',
        concept: 'Running add again copies the current working content into the index.',
        concepts: ['staging-area', 'selective-staging'],
        exactCommand: 'git add README.md',
        progressiveHints: ['Select the changed path again.', 'Use `git add README.md`.', 'Type: git add README.md'],
        estimatedTime: 20,
        expectedOutcome: 'The index entry for README.md changes even though the staged-file count can remain one.',
        checkpointQuestions: ['Why can semantic state change while a count stays constant?'],
        knowledgeCheck: {
          question: 'Can the index change while “1 staged file” remains “1 staged file”?',
          options: ['Yes — the staged content can change', 'No — counts fully describe Git state'],
          correctOption: 0,
          explanation: 'Entity/content changes are more informative than counts alone.',
        },
        assessment: {
          pattern: '^git\\s+add\\s+README\\.md$',
          requiresPrediction: true,
          goal: [{ type: 'staged-includes', path: 'README.md' }],
        },
      },
      {
        id: 'commit2',
        title: 'Record the Second Snapshot',
        description: 'Create a second commit so parent relationships become visible.',
        hint: 'Goal: record the refreshed README.md selection.',
        concept: 'The new commit points to the previous commit as its parent and main advances again.',
        concepts: ['commit', 'branch-movement'],
        exactCommand: 'git commit -m "Update README"',
        progressiveHints: ['Record the index again.', 'Use `git commit -m`.', 'Type: git commit -m "Update README"'],
        estimatedTime: 30,
        expectedOutcome: 'A second commit is created and main advances to it.',
        checkpointQuestions: ['What is the new commit’s parent?'],
        knowledgeCheck: {
          question: 'What happened to the first commit?',
          options: [
            'It stayed immutable and became the parent of the new commit',
            'It was overwritten',
            'It moved to the remote',
          ],
          correctOption: 0,
          explanation: 'New commits extend history; old commits remain unchanged.',
        },
        assessment: {
          pattern: '^git\\s+commit\\s+-m\\s+".+"$',
          requiresPrediction: true,
          goal: [{ type: 'commit-count-at-least', count: 2 }],
        },
      },
      {
        id: 'log1',
        title: 'Read the Commit Chain',
        description: 'Inspect the two recorded commits.',
        hint: 'Goal: read ancestry without modifying it.',
        concept: 'Log is an observation over the commit graph.',
        concepts: ['commit', 'status-orientation'],
        exactCommand: 'git log',
        progressiveHints: ['Use the history observation command.', 'The subcommand is `log`.', 'Type: git log'],
        estimatedTime: 20,
        expectedOutcome: 'Both commits appear newest-first with no state mutation.',
        checkpointQuestions: ['Which commit is HEAD on?'],
        knowledgeCheck: {
          question: 'Does `git log` move HEAD?',
          options: ['No', 'Yes'],
          correctOption: 0,
          explanation: 'Log only reads history.',
        },
        assessment: { pattern: '^git\\s+log$', requiresPrediction: true },
      },
      {
        id: 'show-head',
        title: 'Inspect One Recorded Snapshot',
        description: 'Inspect the current commit as a specific object.',
        hint: 'Goal: show HEAD in detail.',
        concept: '`git show` resolves a commit-ish name and inspects one recorded object.',
        concepts: ['commit', 'diff-inspection'],
        exactCommand: 'git show HEAD',
        progressiveHints: ['Use the one-object inspection command.', 'Use `show` with HEAD.', 'Type: git show HEAD'],
        estimatedTime: 20,
        expectedOutcome: 'The current commit details are displayed with no mutation.',
        checkpointQuestions: ['Why are log and show safe orientation tools?'],
        knowledgeCheck: {
          question: 'What does HEAD name here?',
          options: ['The current commit through the current branch', 'The remote server', 'The staging area'],
          correctOption: 0,
          explanation: 'HEAD is attached to main, which points at the current commit.',
        },
        assessment: { pattern: '^git\\s+show\\s+HEAD$', requiresPrediction: true },
      },
    ],
  },
  {
    id: 'snapshot-transfer',
    title: 'Focused Snapshot Practice',
    icon: '🧪',
    description: 'Solve a changed staging problem without copying the worked sequence',
    objective:
      'Stage only the documentation change when two files have changed, inspect it, and record a focused commit.',
    category: 'basics',
    prerequisites: ['basics'],
    order: 1,
    scenario: 'local/selective-staging',
    mode: 'practice',
    concepts: {
      requires: ['selective-staging', 'diff-inspection'],
      introduces: ['transfer-practice'],
      practices: ['status-orientation'],
      assesses: ['selective-staging', 'transfer-practice'],
    },
    phases: ['predict', 'act', 'inspect', 'explain', 'transfer'],
    steps: [
      {
        id: 'transfer-stage-docs',
        title: 'Stage Only Documentation',
        description: 'README.md and recipes/salad.md both changed. Put only README.md into the candidate snapshot.',
        hint: 'Goal only: end with README.md staged and recipes/salad.md not staged.',
        concept: 'A goal predicate can have more than one valid command sequence.',
        concepts: ['selective-staging', 'transfer-practice'],
        exactCommand: 'git add README.md',
        progressiveHints: [
          'Which layer must contain README.md at the end?',
          'A path-specific add is the shortest solution; add-all plus unstage is another.',
          'One solution: git add README.md',
        ],
        estimatedTime: 45,
        expectedOutcome: 'README.md is staged and recipes/salad.md remains outside the index.',
        checkpointQuestions: ['What alternative valid sequence could reach the same state?'],
        knowledgeCheck: {
          question: 'What makes the task complete?',
          options: [
            'The repository state matches the goal, not one mandatory command string',
            'Only typing `git add .`',
            'The working files disappear',
          ],
          correctOption: 0,
          explanation: 'Practice labs assess the resulting state so multiple safe solutions can be valid.',
        },
        assessment: {
          requiresPrediction: true,
          goal: [
            { type: 'staged-includes', path: 'README.md' },
            { type: 'staged-excludes', path: 'recipes/salad.md' },
          ],
        },
      },
      {
        id: 'transfer-inspect',
        title: 'Prove the Selection',
        description: 'Inspect the candidate snapshot before recording it.',
        hint: 'Goal: verify what the index contains.',
        concept: 'Inspection closes the loop between intention and actual staged state.',
        concepts: ['diff-inspection', 'transfer-practice'],
        exactCommand: 'git diff --staged',
        progressiveHints: ['Compare the index to HEAD.', 'Use staged diff.', 'Type: git diff --staged'],
        estimatedTime: 25,
        expectedOutcome: 'The staged diff contains README.md but not the unrelated salad edit.',
        checkpointQuestions: ['What evidence proves the commit will stay focused?'],
        knowledgeCheck: {
          question: 'Which evidence is strongest before committing?',
          options: [
            'The staged diff contains only the intended path',
            'The terminal prompt looks normal',
            'A branch exists',
          ],
          correctOption: 0,
          explanation: 'Inspecting the index verifies the candidate snapshot itself.',
        },
        assessment: {
          pattern: '^git\\s+diff\\s+--(staged|cached)$',
          requiresPrediction: true,
          goal: [
            { type: 'staged-includes', path: 'README.md' },
            { type: 'staged-excludes', path: 'recipes/salad.md' },
          ],
        },
      },
      {
        id: 'transfer-commit',
        title: 'Record the Focused Commit',
        description: 'Record the selected documentation change while leaving the unrelated working edit uncommitted.',
        hint: 'Goal: create a commit that records the index, not every working edit.',
        concept: 'Focused commits preserve separation between unrelated changes.',
        concepts: ['commit', 'selective-staging', 'transfer-practice'],
        exactCommand: 'git commit -m "Document project"',
        progressiveHints: [
          'Record the candidate snapshot.',
          'Use commit with a message.',
          'One solution: git commit -m "Document project"',
        ],
        estimatedTime: 35,
        expectedOutcome: 'A documentation commit is created while the salad working edit remains outside history.',
        checkpointQuestions: ['Why is the remaining working edit not accidentally committed?'],
        knowledgeCheck: {
          question: 'Why did the salad edit stay out of the commit?',
          options: [
            'It was not in the index',
            'Git ignores all recipe files',
            'Commit records only README by definition',
          ],
          correctOption: 0,
          explanation: 'Commit records the selected index state.',
        },
        assessment: {
          pattern: '^git\\s+commit\\s+-m\\s+".+"$',
          requiresPrediction: true,
          goal: [{ type: 'commit-count-at-least', count: 2 }],
        },
      },
    ],
  },
]
