import type { LessonDefinitionV2 } from '../types'

export const RECOVERY_LESSONS: LessonDefinitionV2[] = [
  {
    id: 'safety-recovery',
    title: 'Recovery Decision Map',
    icon: '🛟',
    description: 'Choose recovery by asking which Git state is actually wrong',
    objective:
      'Distinguish working-tree, index, and recorded-history recovery before reaching for destructive commands.',
    category: 'recovery',
    prerequisites: ['basics'],
    order: 0,
    scenario: 'orientation/empty',
    mode: 'guided',
    concepts: {
      requires: ['working-tree', 'staging-area', 'commit'],
      introduces: ['recovery', 'restore', 'revert', 'reset-modes', 'reflog'],
      practices: ['status-orientation'],
      assesses: ['recovery'],
    },
    phases: ['model', 'retrieve'],
    steps: [
      {
        id: 'danger-map',
        title: 'Ask What You Mean by “Undo”',
        description:
          'An unwanted working edit, an unwanted staged selection, and an unwanted recorded commit are three different problems.',
        hint: 'Identify the wrong layer before choosing a command.',
        concept: 'The least destructive recovery is usually the one that changes only the incorrect layer.',
        concepts: ['recovery', 'restore', 'revert', 'reset-modes'],
        expectedOutcome: 'You can choose an operation family from the state you intend to repair.',
        checkpointQuestions: ['Which layer is wrong?'],
        safetyNote:
          'Orient with status/log before history-moving or file-discarding commands; make a backup ref before destructive experimentation in a real repository.',
        knowledgeCheck: {
          question: 'A commit already shared with collaborators is wrong. Which family best preserves shared history?',
          options: [
            'Create an inverse commit with revert',
            'Move the shared branch backward with reset --hard',
            'Delete .git',
          ],
          correctOption: 0,
          explanation: 'Revert adds history rather than rewriting the shared branch’s existing commits.',
        },
      },
    ],
  },
  {
    id: 'recovery-restore',
    title: 'Recovery Lab: Working Tree & Index',
    icon: '🧽',
    description: 'Unstage a change, then deliberately discard the remaining working edit',
    objective: 'Use restore to repair index/working state without moving commit history.',
    category: 'recovery',
    prerequisites: ['safety-recovery'],
    order: 1,
    scenario: 'recovery/staged',
    mode: 'recovery',
    concepts: {
      requires: ['recovery', 'staging-area'],
      introduces: [],
      practices: ['restore'],
      assesses: ['restore', 'recovery'],
    },
    phases: ['predict', 'act', 'inspect', 'explain', 'transfer'],
    steps: [
      {
        id: 'restore-unstage',
        title: 'Remove README from the Candidate Snapshot',
        description: 'The README edit is useful, but not for this commit. Unstage it without losing the working edit.',
        hint: 'Goal: make the index exclude README.md while keeping its working content.',
        concept: '`restore --staged` repairs the index selection; it does not move HEAD.',
        concepts: ['restore', 'staging-area'],
        exactCommand: 'git restore --staged README.md',
        progressiveHints: [
          'Target the staging/index side of restore.',
          'Use the `--staged` flag.',
          'Type: git restore --staged README.md',
        ],
        estimatedTime: 30,
        expectedOutcome: 'README.md leaves the index while the edited working file remains.',
        checkpointQuestions: ['Which layer changed?'],
        knowledgeCheck: {
          question: 'Did unstaging discard the working edit?',
          options: ['No', 'Yes'],
          correctOption: 0,
          explanation: 'The operation changes the index selection while leaving working content available.',
        },
        assessment: {
          pattern: '^git\\s+restore\\s+--staged\\s+README\\.md$',
          requiresPrediction: true,
          goal: [{ type: 'staged-excludes', path: 'README.md' }],
        },
      },
      {
        id: 'restore-working',
        title: 'Discard the Working Edit',
        description: 'Now intentionally return README.md to its committed content.',
        hint: 'Goal: make working README.md match HEAD again.',
        concept: 'Restoring an unstaged working edit is destructive to that local edit but does not rewrite history.',
        concepts: ['restore', 'recovery'],
        exactCommand: 'git restore README.md',
        progressiveHints: [
          'Restore the working path, not the index.',
          'Use restore without `--staged`.',
          'Type: git restore README.md',
        ],
        estimatedTime: 30,
        safetyNote:
          'This deliberately discards the current unstaged README.md edit. In a real repository, inspect diff first if the content may matter.',
        expectedOutcome: 'Working tree and index are clean relative to HEAD; the commit graph did not move.',
        checkpointQuestions: ['Why was this safer than reset --hard?'],
        knowledgeCheck: {
          question: 'What history changed?',
          options: ['None', 'The current commit was deleted', 'All branch refs moved'],
          correctOption: 0,
          explanation: 'Restore targets file/index state, not the branch pointer.',
        },
        assessment: {
          pattern: '^git\\s+restore\\s+README\\.md$',
          requiresPrediction: true,
          goal: [{ type: 'working-clean' }],
        },
      },
    ],
  },
  {
    id: 'recovery-revert',
    title: 'Recovery Lab: Undo Recorded Work Safely',
    icon: '↩️',
    description: 'Reverse a mistaken commit by adding history instead of rewriting it',
    objective: 'Use revert when an existing recorded commit should remain part of shared ancestry.',
    category: 'recovery',
    prerequisites: ['recovery-restore'],
    order: 2,
    scenario: 'recovery/bad-commit',
    mode: 'recovery',
    concepts: { requires: ['recovery', 'commit'], introduces: [], practices: ['revert'], assesses: ['revert'] },
    phases: ['predict', 'act', 'inspect', 'explain', 'transfer'],
    steps: [
      {
        id: 'revert-bad',
        title: 'Reverse the Mistaken Commit',
        description:
          'The latest README change was committed but should be undone without removing that commit from history.',
        hint: 'Goal: create a new inverse commit.',
        concept: 'Revert preserves the old commit and records the inverse change as new history.',
        concepts: ['revert', 'recovery'],
        exactCommand: 'git revert HEAD',
        progressiveHints: [
          'Choose the recovery operation that adds an inverse commit.',
          'Target HEAD with `revert`.',
          'Type: git revert HEAD',
        ],
        estimatedTime: 35,
        expectedOutcome: 'A third commit reverses the mistaken README content and the working tree is clean.',
        checkpointQuestions: ['Why is the mistaken commit still visible?'],
        knowledgeCheck: {
          question: 'What happened to the mistaken commit?',
          options: ['It remains in history; a new commit reverses its effect', 'It was deleted and its hash reused'],
          correctOption: 0,
          explanation: 'Revert is additive history.',
        },
        assessment: {
          pattern: '^git\\s+revert\\s+HEAD$',
          requiresPrediction: true,
          goal: [{ type: 'commit-count-at-least', count: 3 }, { type: 'working-clean' }],
        },
      },
    ],
  },
  {
    id: 'recovery-reset',
    title: 'Recovery Lab: Reset Modes',
    icon: '🎚️',
    description: 'Observe how soft, mixed, and hard reset affect different layers',
    objective:
      'Predict the branch/index/working-tree consequences of each reset mode and use reflog as recovery evidence.',
    category: 'recovery',
    prerequisites: ['recovery-revert'],
    order: 3,
    scenario: 'recovery/reset-history',
    mode: 'recovery',
    concepts: {
      requires: ['recovery', 'branch-movement'],
      introduces: [],
      practices: ['reset-modes', 'reflog'],
      assesses: ['reset-modes', 'reflog'],
    },
    phases: ['model', 'predict', 'act', 'inspect', 'explain', 'retrieve', 'transfer'],
    steps: [
      {
        id: 'reset-model',
        title: 'Predict the Three Modes',
        description:
          'Soft moves the ref and keeps removed changes staged; mixed moves the ref and unstages; hard also overwrites working files.',
        hint: 'Think of reset as a branch move plus an optional index/worktree reset.',
        concept: 'Reset modes differ by how far the target commit state is propagated.',
        concepts: ['reset-modes'],
        expectedOutcome: 'You can order soft → mixed → hard by affected layers.',
        checkpointQuestions: ['Which mode touches the working tree?'],
        knowledgeCheck: {
          question: 'Which reset mode changes the branch ref but keeps removed commit changes staged?',
          options: ['--soft', '--mixed', '--hard'],
          correctOption: 0,
          explanation: 'Soft moves the ref only, leaving index and working content intact.',
        },
      },
      {
        id: 'reset-soft',
        title: 'Soft Reset One Commit',
        description: 'Move back from the third snapshot while keeping that change selected in the index.',
        hint: 'Goal: move HEAD~1 but preserve the removed commit’s change as staged content.',
        concept: 'Soft reset exposes a former commit as candidate snapshot content.',
        concepts: ['reset-modes'],
        exactCommand: 'git reset --soft HEAD~1',
        progressiveHints: [
          'Choose the ref-only reset mode.',
          'Use `--soft` with HEAD~1.',
          'Type: git reset --soft HEAD~1',
        ],
        estimatedTime: 30,
        safetyNote:
          'Reset rewrites the branch’s visible history. Keep this to local/unshared work unless collaboration policy explicitly permits rewriting.',
        expectedOutcome: 'The branch moves back one commit; the removed salad change remains staged and working.',
        checkpointQuestions: ['Which layers did not get reset?'],
        knowledgeCheck: {
          question: 'After soft reset, where is the removed commit’s change?',
          options: ['Still staged and in the working tree', 'Deleted from all local state'],
          correctOption: 0,
          explanation: 'Only the ref moved.',
        },
        assessment: {
          pattern: '^git\\s+reset\\s+--soft\\s+HEAD~1$',
          requiresPrediction: true,
          goal: [{ type: 'staged-includes', path: 'recipes/salad.md' }],
        },
      },
      {
        id: 'reset',
        title: 'Mixed Reset One More Commit',
        description: 'Move the branch again and clear the index while leaving working content visible.',
        hint: 'Goal: move another commit back and unstage the candidate content.',
        concept: 'Mixed reset (the default) updates the ref and index but preserves working content.',
        concepts: ['reset-modes'],
        exactCommand: 'git reset HEAD~1',
        progressiveHints: ['Use default/mixed reset.', 'No mode flag is required.', 'Type: git reset HEAD~1'],
        estimatedTime: 30,
        safetyNote:
          'Mixed reset rewrites local branch history. Verify the target and avoid rewriting commits others already depend on.',
        expectedOutcome:
          'The branch moves to the base commit, staging becomes empty, and newer working content remains visible.',
        checkpointQuestions: ['Why is the working tree intentionally dirty now?'],
        knowledgeCheck: {
          question: 'What did mixed reset add compared with soft?',
          options: [
            'It reset/cleared the index to the target while preserving working files',
            'It destroyed all working files',
          ],
          correctOption: 0,
          explanation: 'Mixed reaches one layer farther than soft.',
        },
        assessment: {
          pattern: '^git\\s+reset\\s+HEAD~1$',
          requiresPrediction: true,
          goal: [{ type: 'staged-excludes', path: 'recipes/salad.md' }],
        },
      },
      {
        id: 'reset-hard',
        title: 'Hard Reset the Working Tree',
        description: 'Now deliberately make working content match the current HEAD commit.',
        hint: 'Goal: discard the newer working content so all three local states agree.',
        concept: 'Hard reset propagates the target through ref, index, and working tree.',
        concepts: ['reset-modes', 'recovery'],
        exactCommand: 'git reset --hard HEAD',
        progressiveHints: [
          'Use the mode that also replaces working files.',
          'The flag is `--hard`.',
          'Type: git reset --hard HEAD',
        ],
        estimatedTime: 25,
        safetyNote:
          'reset --hard discards uncommitted working changes. Inspect status/diff and create a backup ref when the content matters.',
        expectedOutcome: 'Working tree and index match HEAD and are clean.',
        checkpointQuestions: ['What local data could hard reset destroy?'],
        knowledgeCheck: {
          question: 'Why is hard reset the highest-risk mode?',
          options: [
            'It can discard uncommitted working content as well as reset index/ref state',
            'It only reads history',
          ],
          correctOption: 0,
          explanation: 'Hard reset affects all three local layers.',
        },
        assessment: {
          pattern: '^git\\s+reset\\s+--hard\\s+HEAD$',
          requiresPrediction: true,
          goal: [{ type: 'working-clean' }],
        },
      },
      {
        id: 'reflog-after-reset',
        title: 'Inspect the Ref Movement Record',
        description: 'Use reflog to see the recent reset positions.',
        hint: 'Goal: inspect local pointer history after rewriting the branch.',
        concept: 'Reflog often preserves evidence of commits whose branch name moved away.',
        concepts: ['reflog', 'recovery'],
        exactCommand: 'git reflog',
        progressiveHints: ['Use the local ref-movement log.', 'The command is `reflog`.', 'Type: git reflog'],
        estimatedTime: 25,
        expectedOutcome: 'Recent reset/commit pointer movements are displayed without another mutation.',
        checkpointQuestions: ['How could this help recover a mistakenly reset commit?'],
        knowledgeCheck: {
          question: 'What is reflog most useful for here?',
          options: [
            'Finding recent local ref positions that can identify “lost” commits',
            'Publishing commits to the server',
          ],
          correctOption: 0,
          explanation: 'Reflog is local recovery evidence.',
        },
        assessment: { pattern: '^git\\s+reflog$', requiresPrediction: true },
      },
    ],
  },
  {
    id: 'advanced',
    title: 'Recovery Lab: Stash & Resume',
    icon: '🗄️',
    description: 'Temporarily shelve unfinished work, verify the clean state, and restore it',
    objective: 'Use stash as temporary worktree/index management rather than as permanent history.',
    category: 'recovery',
    prerequisites: ['recovery-reset'],
    order: 4,
    scenario: 'recovery/stash',
    mode: 'recovery',
    concepts: { requires: ['recovery'], introduces: ['stash'], practices: ['status-orientation'], assesses: ['stash'] },
    phases: ['predict', 'act', 'inspect', 'explain', 'transfer'],
    steps: [
      {
        id: 'stash',
        title: 'Shelve the Work in Progress',
        description: 'Temporarily remove the README work from the working tree.',
        hint: 'Goal: get a clean working tree without committing the unfinished edit.',
        concept: 'Stash stores temporary uncommitted state outside the working tree.',
        concepts: ['stash', 'recovery'],
        exactCommand: 'git stash',
        progressiveHints: ['Use the temporary shelving operation.', 'The command family is stash.', 'Type: git stash'],
        estimatedTime: 25,
        expectedOutcome: 'One stash entry exists and the working tree returns to the committed snapshot.',
        checkpointQuestions: ['Why is this not a normal project-history commit?'],
        knowledgeCheck: {
          question: 'What is stash best treated as?',
          options: ['Temporary local shelving for unfinished work', 'A replacement for all commits'],
          correctOption: 0,
          explanation: 'Stash helps change tasks; durable project history belongs in commits.',
        },
        assessment: {
          pattern: '^git\\s+stash$',
          requiresPrediction: true,
          goal: [{ type: 'stash-count', count: 1 }, { type: 'working-clean' }],
        },
      },
      {
        id: 'stash-list',
        title: 'Inspect the Shelf',
        description: 'List stash entries without changing them.',
        hint: 'Goal: confirm the shelved work exists before restoring it.',
        concept: 'Observation before recovery reduces guesswork.',
        concepts: ['stash', 'status-orientation'],
        exactCommand: 'git stash list',
        progressiveHints: ['Use a stash inspection subcommand.', 'The subcommand is `list`.', 'Type: git stash list'],
        estimatedTime: 20,
        expectedOutcome: 'The stash entry is listed and working state is unchanged.',
        checkpointQuestions: ['Why inspect before pop?'],
        knowledgeCheck: {
          question: 'Does `stash list` restore anything?',
          options: ['No', 'Yes'],
          correctOption: 0,
          explanation: 'List is observational.',
        },
        assessment: {
          pattern: '^git\\s+stash\\s+list$',
          requiresPrediction: true,
          goal: [{ type: 'stash-count', count: 1 }],
        },
      },
      {
        id: 'stash-pop',
        title: 'Resume the Work',
        description: 'Restore the latest stash entry into the working tree.',
        hint: 'Goal: bring the unfinished README edit back and remove the stash entry.',
        concept: 'Pop reapplies the stash and removes it from the stash list.',
        concepts: ['stash', 'recovery'],
        exactCommand: 'git stash pop',
        progressiveHints: [
          'Use the stash operation that reapplies and removes the latest entry.',
          'The subcommand is `pop`.',
          'Type: git stash pop',
        ],
        estimatedTime: 25,
        expectedOutcome: 'The README work returns and the stash list becomes empty.',
        checkpointQuestions: ['What should you verify after restoring shelved work?'],
        knowledgeCheck: {
          question: 'What distinguishes pop from list?',
          options: ['Pop changes working state and consumes the entry; list only observes', 'They are identical'],
          correctOption: 0,
          explanation: 'Pop is state-changing recovery.',
        },
        assessment: {
          pattern: '^git\\s+stash\\s+pop$',
          requiresPrediction: true,
          goal: [{ type: 'stash-count', count: 0 }],
        },
      },
    ],
  },
]
