import type { LessonDefinitionV2 } from '../types'

export const REMOTE_LESSONS: LessonDefinitionV2[] = [
  {
    id: 'remotes-intro',
    title: 'Remotes Are Other Repository Copies',
    icon: '🌐',
    description: 'Configure a named connection without pretending the remote is part of your working tree',
    objective: 'Explain a remote name as local configuration for another repository copy.',
    category: 'remotes',
    prerequisites: ['advanced'],
    order: 0,
    scenario: 'remotes/configure',
    mode: 'guided',
    concepts: {
      requires: ['repository'],
      introduces: ['remote'],
      practices: ['status-orientation'],
      assesses: ['remote'],
    },
    phases: ['model', 'predict', 'act', 'inspect', 'explain', 'retrieve'],
    steps: [
      {
        id: 'remote-add',
        title: 'Name Another Repository',
        description: 'Add origin as a local configuration entry pointing at another repository URL.',
        hint: 'Goal: create the remote configuration named origin.',
        concept: 'A remote name is local configuration, not a magical cloud branch.',
        concepts: ['remote'],
        exactCommand: 'git remote add origin https://example.test/recipe-book.git',
        progressiveHints: [
          'Use the remote configuration command.',
          'Add a remote named origin with a URL.',
          'Type: git remote add origin https://example.test/recipe-book.git',
        ],
        estimatedTime: 30,
        expectedOutcome: 'origin is configured locally; no commits are fetched and no working files change.',
        checkpointQuestions: ['What exists locally after this command?'],
        knowledgeCheck: {
          question: 'Did `git remote add` download remote history?',
          options: ['No — it only configured the connection', 'Yes — add always fetches'],
          correctOption: 0,
          explanation: 'Configuration and synchronization are separate operations.',
        },
        assessment: {
          pattern: '^git\\s+remote\\s+add\\s+origin\\s+.+$',
          requiresPrediction: true,
          goal: [{ type: 'remote-exists', remote: 'origin' }],
        },
      },
      {
        id: 'remote-list',
        title: 'Inspect Remote Configuration',
        description: 'List configured remote names and URLs.',
        hint: 'Goal: inspect configuration without contacting or changing the remote.',
        concept: '`remote -v` is an observation command over local configuration.',
        concepts: ['remote', 'status-orientation'],
        exactCommand: 'git remote -v',
        progressiveHints: ['Use the verbose remote listing.', 'The flag is `-v`.', 'Type: git remote -v'],
        estimatedTime: 20,
        expectedOutcome: 'origin and its URL are displayed without state mutation.',
        checkpointQuestions: ['Why can a remote name exist even while offline?'],
        knowledgeCheck: {
          question: 'Where is the name `origin` stored conceptually?',
          options: ['In local repository configuration', 'Inside every commit object', 'Only on the remote server'],
          correctOption: 0,
          explanation: 'origin is a local nickname/configuration entry.',
        },
        assessment: {
          pattern: '^git\\s+remote\\s+-v$',
          requiresPrediction: true,
          goal: [{ type: 'remote-exists', remote: 'origin' }],
        },
      },
    ],
  },
  {
    id: 'remotes-pull',
    title: 'Fetch First, Then Integrate',
    icon: '📥',
    description: 'Update remote-tracking knowledge before changing the current branch',
    objective: 'Distinguish fetch, remote-tracking refs, local branches, and pull as a convenience composition.',
    category: 'remotes',
    prerequisites: ['remotes-intro'],
    order: 1,
    scenario: 'remotes/fetch',
    mode: 'guided',
    concepts: {
      requires: ['remote', 'branch'],
      introduces: ['fetch', 'remote-tracking', 'pull'],
      practices: ['fast-forward', 'status-orientation'],
      assesses: ['fetch', 'remote-tracking', 'pull'],
    },
    phases: ['model', 'predict', 'act', 'inspect', 'explain', 'retrieve'],
    steps: [
      {
        id: 'remote-fetch',
        title: 'Fetch Without Integrating',
        description: 'Download commits and update origin/main while leaving local main/working files alone.',
        hint: 'Goal: update local knowledge of origin without integrating it.',
        concept:
          'Fetch updates local remote-tracking refs; it is deliberately separable from local branch integration.',
        concepts: ['fetch', 'remote-tracking'],
        exactCommand: 'git fetch origin',
        progressiveHints: [
          'Use the synchronization command that only updates remote knowledge.',
          'Fetch from origin.',
          'Type: git fetch origin',
        ],
        estimatedTime: 35,
        expectedOutcome:
          'origin/main exists locally and points at the fetched remote tip; local main has not been implicitly configured as upstream.',
        checkpointQuestions: ['Which ref moved and which did not?'],
        knowledgeCheck: {
          question: 'What does origin/main represent after fetch?',
          options: [
            'A local remote-tracking ref recording the fetched remote branch position',
            'The remote server process itself',
            'Your editable local main branch',
          ],
          correctOption: 0,
          explanation: 'origin/main is local knowledge of the remote branch.',
        },
        assessment: {
          pattern: '^git\\s+fetch\\s+origin$',
          requiresPrediction: true,
          goal: [{ type: 'remote-tracking-ref-exists', ref: 'origin/main' }],
        },
      },
      {
        id: 'remote-create-tracking-branch',
        title: 'Create a Local Tracking Branch Explicitly',
        description:
          'Create review-remote as an editable local branch based on origin/main and deliberately record the upstream relationship.',
        hint: 'Goal: turn fetched knowledge into an explicit local branch with an upstream; do not pretend origin/main itself is editable.',
        concept:
          'A remote-tracking ref such as origin/main is local knowledge. A tracking branch is a separate local branch plus upstream configuration.',
        concepts: ['remote-tracking', 'upstream', 'branch'],
        exactCommand: 'git switch -c review-remote --track origin/main',
        progressiveHints: [
          'Use switch to create a new local branch from the fetched remote-tracking ref.',
          'Add `--track origin/main` while creating review-remote.',
          'Type: git switch -c review-remote --track origin/main',
        ],
        estimatedTime: 35,
        expectedOutcome: 'HEAD is on local review-remote and that branch explicitly tracks origin/main.',
        checkpointQuestions: ['Which object is editable locally: review-remote or origin/main?'],
        knowledgeCheck: {
          question: 'What is the key difference between origin/main and review-remote?',
          options: [
            'origin/main is a remote-tracking ref; review-remote is a local branch configured to track it',
            'They are the same ref with two display names',
          ],
          correctOption: 0,
          explanation: 'Fetching updates origin/main; local work happens on an actual local branch.',
        },
        assessment: {
          pattern: '^git\\s+switch\\s+-c\\s+review-remote\\s+--track\\s+origin/main$',
          requiresPrediction: true,
          goal: [{ type: 'tracking-configured', branch: 'review-remote', remoteRef: 'origin/main' }],
        },
      },
      {
        id: 'remote-return-main',
        title: 'Return to Local Main',
        description: 'Return HEAD to local main before integrating the fetched history there.',
        hint: 'Goal: make main the receiving branch while keeping review-remote and its upstream intact.',
        concept: 'Upstream configuration belongs to a local branch and survives when you switch elsewhere.',
        concepts: ['branch', 'upstream'],
        exactCommand: 'git switch main',
        progressiveHints: [
          'Switch back to the local receiving branch.',
          'The branch is main.',
          'Type: git switch main',
        ],
        estimatedTime: 20,
        expectedOutcome: 'HEAD returns to main; review-remote still tracks origin/main.',
        checkpointQuestions: ['Did switching main change the upstream configuration of review-remote?'],
        knowledgeCheck: {
          question: 'Does switching away remove review-remote’s upstream configuration?',
          options: [
            'No; the relationship remains configured on that local branch',
            'Yes; upstream only exists while checked out',
          ],
          correctOption: 0,
          explanation: 'Tracking configuration is branch metadata, not temporary UI state.',
        },
        assessment: {
          pattern: '^git\\s+switch\\s+main$',
          requiresPrediction: true,
          goal: [
            { type: 'head-branch', branch: 'main' },
            { type: 'tracking-configured', branch: 'review-remote', remoteRef: 'origin/main' },
          ],
        },
      },
      {
        id: 'remote-integrate',
        title: 'Integrate Explicitly',
        description: 'Fast-forward local main to the fetched origin/main.',
        hint: 'Goal: now make local main contain the fetched commits.',
        concept: 'Separating fetch from merge makes the two state transitions visible.',
        concepts: ['remote-tracking', 'fast-forward'],
        exactCommand: 'git merge origin/main',
        progressiveHints: [
          'Use normal history integration with the remote-tracking ref.',
          'Merge origin/main.',
          'Type: git merge origin/main',
        ],
        estimatedTime: 30,
        expectedOutcome: 'Local main fast-forwards to the fetched tip and the working tree updates.',
        checkpointQuestions: ['Why did fetch alone not do this?'],
        knowledgeCheck: {
          question: 'Which operation changed local main?',
          options: ['The explicit merge', 'The earlier fetch', 'remote -v'],
          correctOption: 0,
          explanation: 'Fetch updated origin/main; merge integrated it into main.',
        },
        assessment: { pattern: '^git\\s+merge\\s+origin/main$', requiresPrediction: true },
      },
      {
        id: 'remote-pull-concept',
        title: 'Understand Pull as Convenience',
        description: 'Run pull now that fetch and integration are separately understood.',
        hint: 'Goal: use the convenience operation and recognize that its integration strategy is configured rather than universally “merge”.',
        concept:
          'Pull fetches and then integrates according to the chosen/configured strategy (merge, rebase, or fast-forward policy).',
        concepts: ['pull', 'fetch'],
        exactCommand: 'git pull origin main',
        progressiveHints: [
          'Use the convenience sync+integrate command.',
          'Pull origin main.',
          'Type: git pull origin main',
        ],
        estimatedTime: 25,
        expectedOutcome: 'The already-up-to-date branch remains unchanged after fetch + configured integration.',
        checkpointQuestions: ['Why teach fetch separately before pull?'],
        knowledgeCheck: {
          question: 'Which statement is most accurate?',
          options: [
            'Pull = fetch plus a configured integration strategy',
            'Pull is always and only fetch + merge in every configuration',
          ],
          correctOption: 0,
          explanation: 'Modern Git can integrate pull via merge, rebase, or fast-forward-only policy.',
        },
        assessment: { pattern: '^git\\s+pull\\s+origin\\s+main$', requiresPrediction: true },
      },
    ],
  },
  {
    id: 'remotes-push',
    title: 'Publish & Configure Upstream Explicitly',
    icon: '📤',
    description: 'Push a local branch and deliberately configure its upstream relationship',
    objective: 'Distinguish publishing remote history from configuring future default synchronization.',
    category: 'remotes',
    prerequisites: ['remotes-pull'],
    order: 2,
    scenario: 'remotes/push',
    mode: 'guided',
    concepts: {
      requires: ['remote', 'branch'],
      introduces: ['push', 'upstream'],
      practices: ['remote-tracking'],
      assesses: ['push', 'upstream'],
    },
    phases: ['predict', 'act', 'inspect', 'explain', 'retrieve'],
    steps: [
      {
        id: 'push-upstream',
        title: 'Push and Set Upstream',
        description: 'Publish local main and explicitly remember origin/main as its upstream.',
        hint: 'Goal: publish main and configure the upstream relationship in one deliberate operation.',
        concept: '`-u` / `--set-upstream` changes local tracking configuration in addition to the push.',
        concepts: ['push', 'upstream'],
        exactCommand: 'git push -u origin main',
        progressiveHints: [
          'Use push with the upstream-setting flag.',
          'The short flag is `-u`.',
          'Type: git push -u origin main',
        ],
        estimatedTime: 35,
        expectedOutcome: 'Remote main advances to the local commit and local main records origin/main as its upstream.',
        checkpointQuestions: ['What extra local state did -u create?'],
        knowledgeCheck: {
          question: 'Does plain `git push origin main` necessarily create upstream configuration?',
          options: ['No; use -u/--set-upstream when you intend to configure it', 'Yes, always'],
          correctOption: 0,
          explanation: 'Publishing and upstream configuration are distinct concepts.',
        },
        assessment: {
          pattern: '^git\\s+push\\s+(-u|--set-upstream)\\s+origin\\s+main$',
          requiresPrediction: true,
          goal: [{ type: 'tracking-configured', branch: 'main', remoteRef: 'origin/main' }],
        },
      },
    ],
  },
  {
    id: 'remotes-workflow',
    title: 'Collaboration Workflow Practice',
    icon: '🤝',
    description: 'Publish a local descendant of fetched shared history',
    objective:
      'Operate a basic fetch/integrate/work/publish collaboration loop from repository state rather than recipe memory.',
    category: 'remotes',
    prerequisites: ['remotes-push'],
    order: 3,
    scenario: 'remotes/workflow',
    mode: 'practice',
    concepts: {
      requires: ['fetch', 'push', 'remote-tracking'],
      introduces: ['transfer-practice'],
      practices: ['upstream', 'status-orientation'],
      assesses: ['push', 'transfer-practice'],
    },
    phases: ['predict', 'act', 'inspect', 'explain', 'transfer'],
    steps: [
      {
        id: 'workflow-publish',
        title: 'Publish the Local Collaboration Commit',
        description:
          'The repository already fetched and integrated shared history, then created one local descendant commit. Publish it and establish upstream.',
        hint: 'Goal: make remote main include the local commit and leave an explicit upstream relationship.',
        concept: 'Push is safe when the remote tip is already an ancestor of the local tip.',
        concepts: ['push', 'upstream', 'transfer-practice'],
        exactCommand: 'git push -u origin main',
        progressiveHints: [
          'The local history already contains the fetched remote tip.',
          'Publish main and configure upstream.',
          'One solution: git push -u origin main',
        ],
        estimatedTime: 40,
        expectedOutcome: 'Remote main advances and main tracks origin/main.',
        checkpointQuestions: ['Why is this push a fast-forward on the remote?'],
        knowledgeCheck: {
          question: 'Why can the remote accept this update without discarding collaborator history?',
          options: ['The old remote tip is an ancestor of the local tip', 'Push always overwrites remote history'],
          correctOption: 0,
          explanation: 'Normal push advances the remote ref only when history is compatible.',
        },
        assessment: {
          pattern: '^git\\s+push\\s+(-u|--set-upstream)\\s+origin\\s+main$',
          requiresPrediction: true,
          goal: [{ type: 'tracking-configured', branch: 'main', remoteRef: 'origin/main' }],
        },
      },
    ],
  },
  {
    id: 'remote-rejection-lab',
    title: 'Collaboration Lab: Rejected Push',
    icon: '🚦',
    description: 'Treat a non-fast-forward rejection as safety evidence, then fetch, integrate, and retry',
    objective:
      'Diagnose and recover from a collaborator moving the remote branch without force-pushing over their work.',
    category: 'remotes',
    prerequisites: ['remotes-workflow'],
    order: 4,
    scenario: 'remotes/rejected-push',
    mode: 'recovery',
    concepts: {
      requires: ['push', 'fetch', 'merge-commit'],
      introduces: [],
      practices: ['remote-tracking', 'recovery'],
      assesses: ['push', 'fetch', 'recovery', 'transfer-practice'],
    },
    phases: ['predict', 'act', 'inspect', 'explain', 'transfer'],
    steps: [
      {
        id: 'push-rejected',
        title: 'Observe the Safety Rejection',
        description:
          'A collaborator advanced remote main after your local work began. Try the normal push and expect Git to reject it.',
        hint: 'Goal: see a non-fast-forward rejection without changing remote history.',
        concept: 'A rejected normal push protects remote commits that your local branch does not yet contain.',
        concepts: ['push', 'recovery'],
        exactCommand: 'git push origin main',
        progressiveHints: ['Try the normal non-force push.', 'Push main to origin.', 'Type: git push origin main'],
        estimatedTime: 25,
        expectedOutcome: 'Push is rejected as non-fast-forward and neither local nor remote history is overwritten.',
        checkpointQuestions: ['What is Git protecting?'],
        knowledgeCheck: {
          question: 'What should you do instead of immediately force-pushing?',
          options: ['Fetch the collaborator history, inspect/integrate it, then retry', 'Delete the remote branch'],
          correctOption: 0,
          explanation: 'The rejection is a signal that the remote has history you do not yet contain.',
        },
        assessment: { pattern: '^git\\s+push\\s+origin\\s+main$', requiresPrediction: true, expectedResult: 'failure' },
      },
      {
        id: 'rejection-fetch',
        title: 'Update Remote Knowledge',
        description: 'Fetch the collaborator’s new remote tip.',
        hint: 'Goal: update origin/main without changing local main yet.',
        concept: 'Fetch turns an external change into inspectable local remote-tracking state.',
        concepts: ['fetch', 'remote-tracking', 'recovery'],
        exactCommand: 'git fetch origin',
        progressiveHints: ['Update remote knowledge first.', 'Fetch origin.', 'Type: git fetch origin'],
        estimatedTime: 25,
        expectedOutcome: 'origin/main advances to the collaborator commit; local main remains on local work.',
        checkpointQuestions: ['Which ref changed?'],
        knowledgeCheck: {
          question: 'After fetch, has your local main integrated the collaborator commit?',
          options: ['No — only origin/main moved', 'Yes — fetch always merges'],
          correctOption: 0,
          explanation: 'Fetch separates knowledge update from integration.',
        },
        assessment: {
          pattern: '^git\\s+fetch\\s+origin$',
          requiresPrediction: true,
          goal: [{ type: 'remote-tracking-ref-exists', ref: 'origin/main' }],
        },
      },
      {
        id: 'rejection-integrate',
        title: 'Join Local and Collaborator Work',
        description:
          'Merge origin/main into local main. The changes are on different files, so the lab can create a clean two-parent merge.',
        hint: 'Goal: make local main contain both local and collaborator ancestry.',
        concept: 'Integration creates local history that safely contains the remote tip.',
        concepts: ['merge-commit', 'recovery'],
        exactCommand: 'git merge origin/main',
        progressiveHints: [
          'Integrate the fetched remote-tracking ref.',
          'Merge origin/main.',
          'Type: git merge origin/main',
        ],
        estimatedTime: 35,
        expectedOutcome: 'Local main receives a two-parent merge commit containing both lines of work.',
        checkpointQuestions: ['Why should the next push be acceptable?'],
        knowledgeCheck: {
          question: 'What ancestry condition now holds?',
          options: ['The collaborator remote tip is an ancestor of local main', 'Local main forgot the remote tip'],
          correctOption: 0,
          explanation: 'The merge makes the remote history part of local ancestry.',
        },
        assessment: {
          pattern: '^git\\s+merge\\s+origin/main$',
          requiresPrediction: true,
          goal: [{ type: 'head-parent-count', count: 2 }],
        },
      },
      {
        id: 'rejection-retry',
        title: 'Retry the Safe Push',
        description: 'Publish the now-integrated local main.',
        hint: 'Goal: advance remote main without force.',
        concept: 'After integration, the normal push can fast-forward the remote ref.',
        concepts: ['push', 'transfer-practice'],
        exactCommand: 'git push origin main',
        progressiveHints: ['Retry the same normal push.', 'No force flag is needed.', 'Type: git push origin main'],
        estimatedTime: 25,
        expectedOutcome: 'Remote main advances to the integrated local merge commit.',
        checkpointQuestions: ['What changed between the rejected and accepted push?'],
        knowledgeCheck: {
          question: 'Why did the retry succeed?',
          options: [
            'Local main now contains the remote tip in its ancestry',
            'The second push automatically became force',
          ],
          correctOption: 0,
          explanation: 'The ancestry is now safe for a normal remote ref advance.',
        },
        assessment: { pattern: '^git\\s+push\\s+origin\\s+main$', requiresPrediction: true },
      },
    ],
  },
]
