import type { LessonDefinitionV2 } from '../types'

export const REVIEW_LESSONS: LessonDefinitionV2[] = [
  {
    id: 'git-internals',
    title: 'Git Internals, Abstracted',
    icon: '🧬',
    description:
      'Connect the course model to commits, trees, blobs, refs, HEAD, and index without plumbing-command overload',
    objective:
      'Explain why the beginner model works by mapping it onto Git’s content-addressed object and ref structure.',
    category: 'advanced',
    prerequisites: ['cherry-pick-guided', 'tags-guided'],
    order: 2,
    scenario: 'orientation/empty',
    mode: 'guided',
    concepts: {
      requires: ['commit', 'branch', 'staging-area'],
      introduces: ['commit-object', 'tree-object', 'blob-object'],
      practices: ['head'],
      assesses: ['commit-object', 'tree-object', 'blob-object'],
    },
    phases: ['model', 'retrieve'],
    steps: [
      {
        id: 'internals-commit',
        title: 'Commit → Tree → Content',
        description:
          'A commit stores metadata, parent IDs, and a tree identity; trees recursively name directory entries and blob content.',
        hint: 'The course’s “immutable snapshot” model is a deliberate abstraction over this object graph.',
        concept: 'Commit identity depends on content and ancestry, explaining why rebase/cherry-pick create new IDs.',
        concepts: ['commit-object', 'tree-object', 'blob-object'],
        expectedOutcome: 'You can map commit snapshot language onto commit/tree/blob relationships.',
        checkpointQuestions: ['Why does changing a parent change a commit ID?'],
        knowledgeCheck: {
          question: 'Which object records parent commit IDs?',
          options: ['Commit object', 'Blob object', 'Branch ref only'],
          correctOption: 0,
          explanation: 'Commit metadata includes parent relationships and the tree it records.',
        },
      },
      {
        id: 'internals-refs',
        title: 'Refs Move; Objects Stay',
        description:
          'refs/heads/main stores a commit identity and HEAD normally names the current branch ref; moving a branch does not mutate old commit objects.',
        hint: 'This is Depth C support for the branch-pointer model used throughout the course.',
        concept: 'Refs are mutable names over immutable object identities.',
        concepts: ['branch', 'head', 'commit-object'],
        expectedOutcome: 'You can explain reset as ref/index/worktree manipulation rather than commit mutation.',
        checkpointQuestions: ['What changes during a normal branch advance?'],
        knowledgeCheck: {
          question: 'Which thing is designed to move?',
          options: ['A branch ref such as refs/heads/main', 'An existing commit object’s parent list'],
          correctOption: 0,
          explanation: 'Refs move between immutable objects.',
        },
      },
      {
        id: 'internals-index',
        title: 'Index as Candidate Tree',
        description: 'The index can be understood as the selected content from which the next commit tree is formed.',
        hint: 'This explains selective staging without treating the index as a physical waiting room.',
        concept: 'The index is structured selected state for the next snapshot.',
        concepts: ['staging-area', 'tree-object'],
        expectedOutcome:
          'You can explain why changing one staged path changes the candidate snapshot without moving the working file.',
        checkpointQuestions: ['Why can index content change while staged-file count stays constant?'],
        knowledgeCheck: {
          question: 'What does commit conceptually turn into recorded history?',
          options: ['The selected/index candidate tree', 'Whatever files happen to exist, ignoring the index'],
          correctOption: 0,
          explanation: 'The index is the candidate snapshot state.',
        },
      },
    ],
  },
  {
    id: 'spaced-review',
    title: 'Spaced Retrieval Review',
    icon: '🧠',
    description: 'Retrieve earlier mechanisms after delay instead of rereading them',
    objective: 'Strengthen concept memory using objective retrieval evidence and review scheduling.',
    category: 'advanced',
    prerequisites: ['basics'],
    order: 3,
    scenario: 'orientation/empty',
    mode: 'practice',
    concepts: {
      requires: ['staging-area', 'commit'],
      introduces: [],
      practices: ['branch', 'remote-tracking', 'recovery'],
      assesses: ['staging-area', 'branch', 'remote-tracking', 'recovery'],
    },
    phases: ['retrieve'],
    steps: [
      {
        id: 'review-three-areas',
        title: 'Retrieve the Snapshot Loop',
        description: 'Recall which comparison each diff form performs and what commit records.',
        hint: 'Answer from memory before opening help.',
        concept: 'Retrieval is stronger evidence than “this looks familiar”.',
        concepts: ['staging-area', 'diff-inspection', 'commit'],
        expectedOutcome: 'A timestamped retrieval result is stored for the snapshot concepts.',
        checkpointQuestions: ['What does commit record?'],
        knowledgeCheck: {
          question: 'Which comparison previews exactly what is staged for the next commit?',
          options: ['git diff --staged: index vs HEAD', 'git diff: working tree vs index', 'git remote -v'],
          correctOption: 0,
          explanation: 'Staged diff previews the candidate snapshot.',
        },
      },
      {
        id: 'review-pointers',
        title: 'Retrieve Pointer Semantics',
        description: 'Recall what moves on commit and how fast-forward differs from a merge commit.',
        hint: 'Think refs and topology, not command names.',
        concept: 'Durable Git reasoning depends on pointer and ancestry models.',
        concepts: ['branch', 'branch-movement', 'fast-forward', 'merge-commit'],
        expectedOutcome: 'A timestamped retrieval result is stored for branch/merge concepts.',
        checkpointQuestions: ['When is a merge commit unnecessary?'],
        knowledgeCheck: {
          question: 'A feature tip is a descendant of main and main has no unique commits. What can merge do?',
          options: ['Fast-forward main to the existing feature tip', 'It must create a two-parent commit'],
          correctOption: 0,
          explanation: 'No divergent ancestry needs joining.',
        },
      },
      {
        id: 'review-recovery',
        title: 'Retrieve Recovery Choice',
        description: 'Choose the least destructive operation family from the layer that is wrong.',
        hint: 'Working edit, index selection, and shared history are different recovery problems.',
        concept: 'Recovery is state diagnosis, not a list of scary undo commands.',
        concepts: ['recovery', 'restore', 'revert'],
        expectedOutcome: 'A timestamped recovery retrieval result is stored.',
        checkpointQuestions: ['What should shared-history undo prefer?'],
        knowledgeCheck: {
          question:
            'A useful working edit was staged accidentally but should remain in the file. What is the narrowest recovery?',
          options: ['git restore --staged <path>', 'git reset --hard', 'Delete the branch'],
          correctOption: 0,
          explanation: 'Only the index selection is wrong.',
        },
      },
      {
        id: 'review-remotes',
        title: 'Retrieve Remote-Tracking Semantics',
        description: 'Recall what fetch changes before any integration or push happens.',
        hint: 'Separate another repository, local remote-tracking knowledge, and your editable local branch.',
        concept: 'Remote collaboration is easier to reason about when those three things remain distinct.',
        concepts: ['remote', 'remote-tracking', 'fetch', 'upstream'],
        expectedOutcome: 'A timestamped retrieval result is stored for remote-state reasoning.',
        checkpointQuestions: ['What does fetch move locally?'],
        knowledgeCheck: {
          question: 'Immediately after `git fetch origin`, which statement is most accurate?',
          options: [
            'origin/main may move locally while editable main and working files remain unchanged',
            'main always advances and working files are replaced',
            'fetch automatically configures upstream for every local branch',
          ],
          correctOption: 0,
          explanation: 'Fetch updates local remote-tracking knowledge and leaves integration as a separate choice.',
        },
      },
    ],
  },
  {
    id: 'collaboration-capstone',
    title: 'Capstone: Preserve Both Sides of Collaboration',
    icon: '🛰️',
    description: 'Publish local work after a collaborator moved the remote branch, without overwriting either history',
    objective:
      'Diagnose a diverged remote state and finish with local main and remote main aligned on history containing both lines of work.',
    category: 'advanced',
    prerequisites: ['remote-rejection-lab'],
    order: 4,
    scenario: 'remotes/rejected-push',
    mode: 'challenge',
    concepts: {
      requires: ['fetch', 'push', 'remote-tracking', 'merge-commit'],
      introduces: [],
      practices: ['recovery', 'status-orientation'],
      assesses: ['transfer-practice', 'remote-tracking', 'push'],
    },
    phases: ['predict', 'act', 'inspect', 'explain', 'transfer'],
    steps: [
      {
        id: 'collaboration-capstone-goal',
        title: 'Align Local and Remote Without Losing Work',
        description:
          'Local main has one unpublished commit and remote main has one collaborator commit you do not yet contain. Finish with both histories integrated locally and the integrated result published normally.',
        hint: 'Goal: local main and remote main end at the same integrated commit; do not force-push.',
        concept:
          'Collaboration transfer is proven by ancestry and final ref state, not by memorizing one synchronization recipe.',
        concepts: ['transfer-practice', 'remote-tracking', 'push', 'recovery'],
        progressiveHints: [
          'First update your local knowledge of the remote before trying to integrate anything.',
          'A safe path is fetch → integrate the fetched remote-tracking ref → normal push.',
          'One solution: git fetch origin → git merge origin/main → git push origin main.',
        ],
        referenceSolution: ['git fetch origin', 'git merge origin/main', 'git push origin main'],
        estimatedTime: 150,
        expectedOutcome:
          'Local main and remote main point at the same integrated commit containing both local and collaborator ancestry.',
        checkpointQuestions: ['Which final ref relationship proves neither side was overwritten?'],
        knowledgeCheck: {
          question: 'What makes this collaboration capstone complete?',
          options: [
            'Local and remote main end aligned on an integrated history containing both lines of work',
            'A force push makes the error disappear',
          ],
          correctOption: 0,
          explanation: 'The outcome must preserve both ancestries and publish the integrated result normally.',
        },
        assessment: {
          requiresPrediction: true,
          goal: [{ type: 'remote-branch-matches-local', remote: 'origin', remoteBranch: 'main', localBranch: 'main' }],
        },
      },
    ],
  },
  {
    id: 'challenge-mode',
    title: 'Capstone: Goal Before Command',
    icon: '🏁',
    description: 'Solve an unfamiliar small repository goal with hints disabled by default',
    objective: 'Transfer the model to a changed repository shape without reproducing a shown command recipe.',
    category: 'advanced',
    prerequisites: ['git-internals', 'collaboration-capstone', 'advanced'],
    order: 5,
    scenario: 'challenge/capstone',
    mode: 'challenge',
    concepts: {
      requires: ['selective-staging', 'branch', 'commit', 'recovery'],
      introduces: [],
      practices: ['status-orientation'],
      assesses: ['transfer-practice', 'branch-movement', 'selective-staging'],
    },
    phases: ['predict', 'act', 'inspect', 'explain', 'transfer'],
    steps: [
      {
        id: 'challenge-small-feature',
        title: 'Ship the Documentation Fix on Its Own Branch',
        description:
          'README.md already contains one uncommitted documentation fix. Create a branch named docs-fix, record only that change there, and finish with a clean working tree on docs-fix.',
        hint: 'Goal: branch docs-fix exists, HEAD is on it, at least one new commit records the edit, and working/index state is clean.',
        concept: 'Capstones are evaluated by repository outcome rather than one exact command sequence.',
        concepts: ['transfer-practice', 'branch-movement', 'selective-staging'],
        progressiveHints: [
          'Which ref should receive the new commit?',
          'You need a branch operation, selective staging, and a commit.',
          'A short path is: switch -c docs-fix → add README.md → commit.',
        ],
        referenceSolution: ['git switch -c docs-fix', 'git add README.md', 'git commit -m "Document capstone fix"'],
        estimatedTime: 120,
        expectedOutcome:
          'docs-fix contains the recorded documentation change; main remains at the base commit and the working tree is clean.',
        checkpointQuestions: ['Which state evidence proves the goal rather than merely proving commands were typed?'],
        knowledgeCheck: {
          question: 'What makes this capstone complete?',
          options: [
            'The declared repository-state goal is satisfied',
            'One exact memorized command sequence was copied',
          ],
          correctOption: 0,
          explanation: 'Transfer means reaching the intended state in a changed context.',
        },
        assessment: {
          requiresPrediction: true,
          goal: [
            { type: 'branch-exists', branch: 'docs-fix' },
            { type: 'head-branch', branch: 'docs-fix' },
            { type: 'commit-count-at-least', count: 2 },
            { type: 'working-clean' },
          ],
        },
      },
    ],
  },
]
