import type { LessonDefinitionV2 } from '../types'

export const SELECTIVE_HISTORY_LESSONS: LessonDefinitionV2[] = [
  {
    id: 'tags-guided',
    title: 'Guided Tags',
    icon: '🏷️',
    description: 'Attach a stable release name to one commit and inspect what it names',
    objective: 'Distinguish a stable tag name from a moving branch ref.',
    category: 'advanced',
    prerequisites: ['basics'],
    order: 0,
    scenario: 'selective-history/base',
    mode: 'guided',
    concepts: {
      requires: ['commit', 'branch'],
      introduces: ['tag'],
      practices: ['status-orientation'],
      assesses: ['tag'],
    },
    phases: ['model', 'predict', 'act', 'inspect', 'explain', 'retrieve'],
    steps: [
      {
        id: 'tag-orient',
        title: 'Orient on the Release Candidate',
        description: 'Inspect history before naming a commit.',
        hint: 'Goal: verify the commit you intend to name.',
        concept: 'A stable name is only useful when you know which object it identifies.',
        concepts: ['tag', 'status-orientation'],
        exactCommand: 'git log',
        progressiveHints: ['Inspect history first.', 'Use log.', 'Type: git log'],
        estimatedTime: 20,
        expectedOutcome: 'The release-candidate commit is shown without mutation.',
        checkpointQuestions: ['Which commit will the tag identify?'],
        knowledgeCheck: {
          question: 'Why inspect before tagging?',
          options: [
            'A tag should deliberately identify the intended commit',
            'Tags automatically choose the oldest commit',
          ],
          correctOption: 0,
          explanation: 'Naming is meaningful only when the target is deliberate.',
        },
        assessment: { pattern: '^git\\s+log$', requiresPrediction: true },
      },
      {
        id: 'tag-create',
        title: 'Create the Stable Name',
        description: 'Create v1.0 at the current commit.',
        hint: 'Goal: add a stable release name without moving the branch.',
        concept: 'A tag normally keeps naming the same commit while a branch can advance later.',
        concepts: ['tag'],
        exactCommand: 'git tag v1.0',
        progressiveHints: ['Use the stable-name command.', 'Create tag v1.0.', 'Type: git tag v1.0'],
        estimatedTime: 25,
        expectedOutcome: 'v1.0 appears in the tag list and identifies the current commit.',
        checkpointQuestions: ['How will v1.0 differ from main after another commit?'],
        knowledgeCheck: {
          question: 'What normally happens to v1.0 after main gets another commit?',
          options: ['v1.0 stays on the release commit while main moves', 'v1.0 follows main automatically'],
          correctOption: 0,
          explanation: 'Tags are stable names; branches are movable refs.',
        },
        assessment: {
          pattern: '^git\\s+tag\\s+v1\\.0$',
          requiresPrediction: true,
          goal: [{ type: 'tag-exists', tag: 'v1.0' }],
        },
      },
      {
        id: 'tag-list',
        title: 'List Tags',
        description: 'Inspect the stable names in the repository.',
        hint: 'Goal: confirm v1.0 exists.',
        concept: 'Listing tags is observation.',
        concepts: ['tag', 'status-orientation'],
        exactCommand: 'git tag',
        progressiveHints: ['Use tag without a name.', 'List tags.', 'Type: git tag'],
        estimatedTime: 15,
        expectedOutcome: 'v1.0 is displayed without state mutation.',
        checkpointQuestions: ['What does the name buy a human reader?'],
        knowledgeCheck: {
          question: 'Did listing tags move any ref?',
          options: ['No', 'Yes'],
          correctOption: 0,
          explanation: 'Listing is observational.',
        },
        assessment: { pattern: '^git\\s+tag$', requiresPrediction: true, goal: [{ type: 'tag-exists', tag: 'v1.0' }] },
      },
      {
        id: 'tag-show',
        title: 'Resolve the Name to Its Commit',
        description: 'Inspect the commit identified by v1.0.',
        hint: 'Goal: prove the tag resolves to recorded history.',
        concept: 'Git commands accepting a commit-ish can resolve stable tag names.',
        concepts: ['tag', 'commit'],
        exactCommand: 'git show v1.0',
        progressiveHints: ['Use the one-object inspection command.', 'Show v1.0.', 'Type: git show v1.0'],
        estimatedTime: 20,
        expectedOutcome: 'The release-candidate commit is displayed through its v1.0 name.',
        checkpointQuestions: ['Why is a human-readable stable name useful?'],
        knowledgeCheck: {
          question: 'What did `git show v1.0` change?',
          options: ['Nothing; it resolved and displayed the named commit', 'It moved main to v1.0'],
          correctOption: 0,
          explanation: 'Show is observation.',
        },
        assessment: {
          pattern: '^git\\s+show\\s+v1\\.0$',
          requiresPrediction: true,
          goal: [{ type: 'tag-exists', tag: 'v1.0' }],
        },
      },
    ],
  },
  {
    id: 'cherry-pick-guided',
    title: 'Guided Cherry-Pick',
    icon: '🍒',
    description: 'Replay one selected fix without merging the whole source branch',
    objective: 'Explain cherry-pick as a new commit carrying one selected commit’s change.',
    category: 'advanced',
    prerequisites: ['branches', 'merging'],
    order: 1,
    scenario: 'selective-history/cherry-pick',
    mode: 'guided',
    concepts: {
      requires: ['branch', 'commit'],
      introduces: ['cherry-pick'],
      practices: ['status-orientation'],
      assesses: ['cherry-pick'],
    },
    phases: ['model', 'predict', 'act', 'inspect', 'explain', 'retrieve'],
    steps: [
      {
        id: 'cherry-pick-orient',
        title: 'Orient on Main',
        description: 'Inspect current history before selectively copying a fix.',
        hint: 'Goal: verify main is the receiving branch.',
        concept: 'Cherry-pick writes a new commit on the current branch.',
        concepts: ['cherry-pick', 'head'],
        exactCommand: 'git log',
        progressiveHints: ['Inspect current history.', 'Use log.', 'Type: git log'],
        estimatedTime: 20,
        expectedOutcome: 'Current main history is shown without the source fix applied.',
        checkpointQuestions: ['Which branch will receive the new commit?'],
        knowledgeCheck: {
          question: 'Where will cherry-pick write?',
          options: ['The current main branch', 'The source branch automatically'],
          correctOption: 0,
          explanation: 'Cherry-pick applies selected change to the current branch.',
        },
        assessment: {
          pattern: '^git\\s+log$',
          requiresPrediction: true,
          goal: [{ type: 'head-branch', branch: 'main' }],
        },
      },
      {
        id: 'cherry-pick-find-commit',
        title: 'Inspect the Source Fix',
        description: 'Use the source branch name as a commit-ish and inspect its tip.',
        hint: 'Goal: verify the change you intend to replay.',
        concept: 'A branch name can resolve to the commit at its tip.',
        concepts: ['cherry-pick', 'branch'],
        exactCommand: 'git show fix-source',
        progressiveHints: ['Inspect the source branch tip.', 'Use show with fix-source.', 'Type: git show fix-source'],
        estimatedTime: 20,
        expectedOutcome: 'The Critical pasta fix commit is displayed without changing main.',
        checkpointQuestions: ['Why inspect a selected commit before applying it?'],
        knowledgeCheck: {
          question: 'Is `fix-source` itself copied onto main?',
          options: [
            'No; its tip change is replayed as a new commit',
            'Yes; branch names are duplicated by cherry-pick',
          ],
          correctOption: 0,
          explanation: 'Cherry-pick copies a change, not a branch ref.',
        },
        assessment: { pattern: '^git\\s+show\\s+fix-source$', requiresPrediction: true },
      },
      {
        id: 'cherry-pick-apply',
        title: 'Replay the Selected Fix',
        description: 'Apply only the source branch tip change to main.',
        hint: 'Goal: create one new main commit containing the selected fix.',
        concept: 'Cherry-pick creates a new commit identity because the parent/context differs.',
        concepts: ['cherry-pick', 'commit'],
        exactCommand: 'git cherry-pick fix-source',
        progressiveHints: [
          'Use the selective history replay command.',
          'Cherry-pick fix-source.',
          'Type: git cherry-pick fix-source',
        ],
        estimatedTime: 35,
        safetyNote:
          'Cherry-pick duplicates a change as a new commit on the current branch and can conflict if the target context differs; inspect both branches first.',
        expectedOutcome: 'main receives a new Critical pasta fix commit while the source branch remains intact.',
        checkpointQuestions: ['Why is the new commit ID different?'],
        knowledgeCheck: {
          question: 'Did main receive the exact same commit object?',
          options: ['No; it received a new commit replaying that change', 'Yes; one commit object has two parents now'],
          correctOption: 0,
          explanation: 'The new parent/context gives the replayed commit a new identity.',
        },
        assessment: {
          pattern: '^git\\s+cherry-pick\\s+fix-source$',
          requiresPrediction: true,
          goal: [{ type: 'commit-message-exists', message: 'Critical pasta fix' }],
        },
      },
      {
        id: 'cherry-pick-verify',
        title: 'Verify the Result',
        description: 'Inspect main after selective replay.',
        hint: 'Goal: confirm a new commit exists on main.',
        concept: 'Always inspect history after selective rewriting/replay operations.',
        concepts: ['cherry-pick', 'status-orientation'],
        exactCommand: 'git log',
        progressiveHints: ['Inspect history again.', 'Use log.', 'Type: git log'],
        estimatedTime: 20,
        expectedOutcome: 'The replayed fix appears as a new main commit.',
        checkpointQuestions: ['How is this different from merging fix-source?'],
        knowledgeCheck: {
          question: 'What history did cherry-pick omit?',
          options: ['Any other source-branch commits not selected', 'All main history'],
          correctOption: 0,
          explanation: 'Cherry-pick is selective rather than whole-branch integration.',
        },
        assessment: {
          pattern: '^git\\s+log$',
          requiresPrediction: true,
          goal: [{ type: 'commit-message-exists', message: 'Critical pasta fix' }],
        },
      },
    ],
  },
]
