import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const html = await readFile('app-hub-v11/index.html', 'utf8');

assert.doesNotMatch(html, /Artifact cockpit/, 'v11 should remove the old artifact cockpit hero panel');
assert.match(html, /id="filterPanel"/, 'left sidebar should include an upper filtering panel');
assert.match(html, /id="lobbyPanel"/, 'left sidebar should include a lower lobby/users/chat panel');
assert.match(html, /id="tagFilter"/, 'v11 should render reusable tag filter controls');
assert.match(html, /id="modeAnd"/, 'tag filter should expose AND mode');
assert.match(html, /id="modeOr"/, 'tag filter should expose OR mode');
assert.match(html, /id="onlineUsers"/, 'lobby panel should show online users');
assert.match(html, /id="chatChannels"/, 'lobby panel should allow chat channel spawning');
assert.match(html, /id="spawnChatChannel"/, 'lobby panel should expose chat channel spawn control');
assert.match(html, /id="joinGamePrompt"/, 'lobby panel should expose join-game prompt/status');
assert.match(html, /id="resultsPanel"/, 'center upper panel should show filtered results');
assert.match(html, /id="viewCards"/, 'results should be switchable to cards');
assert.match(html, /id="viewList"/, 'results should be switchable to list');
assert.match(html, /data-launch="inline"/, 'result items should expose inline icon launch buttons');
assert.match(html, /data-launch="fullscreen"/, 'result items should expose fullscreen icon launch buttons');
assert.match(html, /data-launch="floating"/, 'result items should expose floating icon launch buttons');
assert.match(html, /data-launch="newWindow"/, 'result items should expose new-window icon launch buttons');
assert.match(html, /id="appDeck"/, 'v11 should include the v9-style inline app deck');
assert.match(html, /id="appDeckTabs"/, 'inline app deck should include tabs');
assert.match(html, /id="appDeckBody"/, 'inline app deck should include body panels');
assert.match(html, /id="eventLog"/, 'v11 should include a reusable event log panel');
assert.match(html, /createInlineTabDeck/, 'v11 should wire inline tabs through lib/launcher.js');
assert.match(html, /createEventLog/, 'v11 should wire event log through lib/event-log.js');
assert.match(html, /filterArtifactsAdvanced/, 'v11 should wire filtering through lib/menu.js');
assert.doesNotMatch(html, /border-radius\s*:\s*(?!0\b)[^;]+;/, 'v11 shell should use square edges, not rounded corners');
assert.match(html, /id="sidebarResizeHandle"/, 'v11 should expose a draggable border between sidebar and main panel');
assert.match(html, /id="sidebarSplitResizeHandle"/, 'v11 should expose a draggable border between filter and lobby panels');
assert.match(html, /createResizablePanels/, 'v11 should wire panel resizing through lib/resizable-panels.js');
assert.match(html, /--sidebar-width/, 'v11 should persist sidebar width as a CSS variable');
assert.match(html, /--filter-panel-fr/, 'v11 should persist sidebar split as a CSS variable');
assert.match(html, /class="pixel-muse"/, 'v11 should include a small artistic endeavour sprite motif');
assert.match(html, /pixel-noise/, 'v11 should add slight pixel-art noisiness');
assert.match(html, /image-rendering:\s*pixelated/, 'v11 should lean into pixel rendering');
assert.match(html, /font-size:\.65rem/, 'v11 tags should be tiny like v9');
assert.match(html, /gap:\.35rem/, 'v11 should reduce visual gaps');
assert.match(html, /box-shadow:4px 4px 0/, 'v11 should have harder nerdy edge shadows');
assert.match(html, /tagColorStyle/, 'v11 result tag pills should use shared tag color coding');
assert.match(html, /--tag-hue/, 'v11 should expose CSS variables for per-tag colors');

console.log('app-hub v11 index UI contract OK');

assert.match(html, /id="workspacePane"/, 'v11 should include a bottom split workspace pane for inline apps and logs');
assert.match(html, /id="workspaceResizeHandle"/, 'workspace pane should be height-resizable');
assert.match(html, /--workspace-height/, 'workspace pane height should persist as a CSS variable');
assert.match(html, /id="workspaceTabs"/, 'workspace pane should expose shared tabs');
assert.match(html, /data-workspace-tab="appDeck"/, 'workspace tabs should include the inline app deck');
assert.match(html, /data-workspace-tab="eventLog"/, 'workspace tabs should include the event log');
assert.match(html, /id="eventLogPanel"/, 'event log should live inside the workspace tab pane');
assert.match(html, /setWorkspaceTab/, 'v11 should switch workspace pane tabs');
assert.match(html, /workspacePane\.classList\.add\('active'\)/, 'opening inline apps should show the split workspace pane');
assert.match(html, /id="defaultAction"/, 'v11 should expose a default artifact action selector');
assert.match(html, /readHubSetting\('defaultAction', 'newWindow'\)/, 'default artifact action should be new window');
assert.match(html, /data-artifact-title/, 'artifact title should be its own default-action trigger');
assert.match(html, /openSelected\(defaultAction\)/, 'title clicks should trigger the configured default action');
assert.doesNotMatch(html, /<section id="appDeck" class="card app-deck">/, 'app deck should not spawn as a standalone card below results');
assert.doesNotMatch(html, /<section class="card stack"><div class="row between"><strong>Event log<\/strong>/, 'event log should not be a standalone section below results');

assert.match(html, /class="badger-runner"/, 'v11 should show the bdg.gif badger runner at the bottom');
assert.match(html, /src="\.\.\/bdg\.gif"/, 'badger runner should use bdg.gif from the artifacts root');
assert.match(html, /@keyframes badger-run/, 'badger runner should animate across the bottom of the hub');
assert.match(html, /\.workspace-pane[\s\S]*resize:\s*vertical/, 'workspace pane should be directly resizable by the browser too');
assert.match(html, /\.workspace-pane[\s\S]*overflow:\s*auto/, 'workspace pane contents below results should be scrollable');
assert.match(html, /\.workspace-panel[\s\S]*overflow:\s*auto/, 'workspace tab panels should scroll instead of clipping content');
assert.match(html, /\.app-deck-panel[\s\S]*overflow:\s*auto/, 'inline app panels should scroll when embedded apps overflow');
assert.match(html, /\.results-panel[\s\S]*overflow:\s*auto/, 'filtered results panel should remain scrollable');
assert.match(html, /\.resize-handle[\s\S]*touch-action:\s*none/, 'drag handles should disable touch scrolling during resize');
assert.match(html, /workspacePane\.style\.resize\s*=\s*'vertical'/, 'v11 should explicitly enable browser vertical resize on the workspace pane');

assert.doesNotMatch(html, /drop-shadow\(/, 'badger runner should not use a drop shadow');
