import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const html = await readFile(new URL('../sprite_extractor.html', import.meta.url), 'utf8');

assert.match(html, /<title>Sprite Extractor<\/title>/, 'artifact should have the extractor title');
assert.match(html, /id="autoDetectBtn"/, 'artifact should offer automatic sprite detection');
assert.match(html, /id="manualGridBtn"/, 'artifact should allow manual grid setup');
assert.match(html, /id="trimAlpha"[^>]*checked/, 'alpha trimming should be enabled by default');
assert.match(html, /id="spriteList"/, 'artifact should include a sane sprite naming UI');
assert.match(html, /downloadNamedZip/, 'artifact should export named sprites as a zip');
assert.match(html, /downloadAllImages/, 'artifact should export named sprites as individual images');
assert.match(html, /findAlphaBounds/, 'artifact should reduce matching sprites to non-alpha bounds');
assert.match(html, /detectSpritesByAlpha/, 'artifact should detect sprites from alpha components');
assert.match(html, /sanitizeName/, 'artifact should sanitize exported file names');
assert.match(html, /id="previewZoom"/, 'artifact should include zoom controls for cleaner previews');
assert.match(html, /id="previewMode"/, 'artifact should allow switching preview backgrounds');
assert.match(html, /id="splitDirection"/, 'artifact should make grid splitting order explicit');
assert.match(html, /id="nameListText"/, 'artifact should allow pasting/restoring sprite name lists');
assert.match(html, /applyNameList/, 'artifact should assign stored name lists to extracted sprites');
assert.match(html, /saveNameListPreset/, 'artifact should store reusable sprite name lists');
assert.match(html, /restoreNameListPreset/, 'artifact should restore reusable sprite name lists');
assert.match(html, /renderSplitPreview/, 'artifact should render a clean split preview overlay');
assert.match(html, /assignNamesToGrid/, 'artifact should assign names to sprite grids in order');
assert.match(html, /id="shortcutHelp"/, 'artifact should document keyboard shortcuts');
assert.match(html, /handleKeyboardShortcut/, 'artifact should implement keyboard shortcuts');
assert.match(html, /id="cropMode"/, 'artifact should expose crop modes');
assert.match(html, /id="cropPadding"/, 'artifact should expose crop padding');
assert.match(html, /id="connectivity"/, 'artifact should expose auto-detection connectivity');
assert.match(html, /id="mergeGap"/, 'artifact should expose component merge gap');
assert.match(html, /id="sortMode"/, 'artifact should expose sprite ordering flexibility');
assert.match(html, /id="setupPresetSelect"/, 'artifact should store and restore extraction setup presets');
assert.match(html, /saveSetupPreset/, 'artifact should save crop/detection/grid setup presets');
assert.match(html, /restoreSetupPreset/, 'artifact should restore crop/detection/grid setup presets');
assert.match(html, /exportSetupJson/, 'artifact should export setup JSON');
assert.match(html, /importSetupJson/, 'artifact should import setup JSON');
assert.match(html, /mergeNearbyBoxes/, 'artifact should support merging nearby detected components');
assert.match(html, /applyCropSetup/, 'artifact should apply crop mode and padding to extracted sprites');
assert.match(html, /id="cellEditorPanel"/, 'artifact should include an image-by-image cell editor panel');
assert.match(html, /id="cellEditorCanvas"/, 'artifact should include a focused per-sprite border editor canvas');
assert.match(html, /id="prevSpriteBtn"/, 'artifact should allow stepping to previous sprite in the editor');
assert.match(html, /id="nextSpriteBtn"/, 'artifact should allow stepping to next sprite in the editor');
assert.match(html, /id="resetSpriteBoundsBtn"/, 'artifact should allow resetting a sprite border edit');
assert.match(html, /openCellEditor/, 'artifact should open a per-sprite border editor after extraction');
assert.match(html, /adjustActiveSpriteBounds/, 'artifact should adjust active sprite bounds manually');
assert.match(html, /handleCellEditorKeydown/, 'artifact should support hjkl and HJKL keyboard border editing');
assert.match(html, /renderCellEditor/, 'artifact should render the active sprite edit canvas');
assert.match(html, /rebuildSpriteFromBounds/, 'artifact should rebuild sprite images from edited bounds');
assert.match(html, /cellEditorStep/, 'artifact should expose editor step size for border adjustments');
assert.match(html, /h j k l/, 'artifact should document hjkl border shortcuts');
assert.match(html, /H J K L/, 'artifact should document shifted coarse border shortcuts');
assert.match(html, /id="appendExtraction"[^>]*checked/, 'artifact should append extraction passes to one export by default');
assert.match(html, /id="clearSpritesBtn"/, 'artifact should allow clearing accumulated extracted sprites');
assert.match(html, /id="batchName"/, 'artifact should allow naming extraction batches');
assert.match(html, /state\.batches/, 'artifact should track multiple upload/grid extraction batches');
assert.match(html, /appendSpritesFromBoxes/, 'artifact should append new grid/auto extraction results instead of replacing exports');
assert.match(html, /batchId/, 'artifact should keep batch metadata per exported sprite');
assert.match(html, /id="backgroundToolPanel"/, 'artifact should include sophisticated background-to-alpha tools');
assert.match(html, /id="backgroundMode"/, 'artifact should expose background removal modes');
assert.match(html, /id="backgroundTolerance"/, 'artifact should expose color distance tolerance');
assert.match(html, /id="backgroundFeather"/, 'artifact should expose feather/soft-alpha controls');
assert.match(html, /id="backgroundPickBtn"/, 'artifact should allow picking background color from the sheet');
assert.match(html, /id="applyBackgroundToActiveBtn"/, 'artifact should apply background removal to active sprite');
assert.match(html, /id="applyBackgroundToAllBtn"/, 'artifact should apply background removal to all sprites');
assert.match(html, /id="restoreAlphaBtn"/, 'artifact should restore the active sprite alpha/source image');
assert.match(html, /sampleBackgroundColor/, 'artifact should sample background colors from canvas pixels');
assert.match(html, /applyBackgroundAlphaTool/, 'artifact should convert selected backgrounds to alpha');
assert.match(html, /removeBackgroundByChroma/, 'artifact should support chroma/color-key background removal');
assert.match(html, /removeBackgroundByCornerFlood/, 'artifact should support flood-fill corner background removal');
assert.match(html, /removeBackgroundByLuminance/, 'artifact should support luminance-based matte cleanup');
assert.match(html, /colorDistance/, 'artifact should use color distance for background matching');
assert.match(html, /softAlphaFromDistance/, 'artifact should support feathered alpha falloff');

const catalog = await readFile(new URL('../app-hub-v11/artifacts.source.json', import.meta.url), 'utf8');
assert.match(catalog, /"id": "sprite-extractor"/, 'v11 artifact catalog should include the extractor');
assert.match(catalog, /"href": "\.\.\/sprite_extractor\.html"/, 'catalog should launch the root extractor artifact');

console.log('sprite extractor artifact contract OK');
