import type { ConceptDefinition } from './types'

export const CONCEPTS: ConceptDefinition[] = [
  {
    id: 'version-control',
    title: 'Version control',
    depth: 'A',
    description: 'Recorded project history instead of copied folders.',
  },
  { id: 'repository', title: 'Repository', depth: 'A', description: 'Project files plus Git metadata and history.' },
  { id: 'working-tree', title: 'Working tree', depth: 'A', description: 'Files currently visible and editable.' },
  {
    id: 'staging-area',
    title: 'Staging area / index',
    depth: 'A',
    description: 'Selected content for the next commit.',
  },
  {
    id: 'selective-staging',
    title: 'Selective staging',
    depth: 'A',
    description: 'Choose exactly which path content belongs in the next snapshot.',
  },
  {
    id: 'diff-inspection',
    title: 'Difference inspection',
    depth: 'A',
    description: 'Compare working, index, and committed content before recording it.',
  },
  {
    id: 'commit',
    title: 'Commit',
    depth: 'A',
    description: 'An immutable recorded snapshot with parent relationships.',
  },
  {
    id: 'status-orientation',
    title: 'Status orientation',
    depth: 'A',
    description: 'Inspect before and after changing repository state.',
  },
  { id: 'branch', title: 'Branch', depth: 'B', description: 'A movable name pointing at a commit.' },
  { id: 'head', title: 'HEAD', depth: 'B', description: 'The learner’s current position in history.' },
  {
    id: 'branch-movement',
    title: 'Branch movement',
    depth: 'B',
    description: 'Committing moves the current branch while other branches stay put.',
  },
  {
    id: 'fast-forward',
    title: 'Fast-forward merge',
    depth: 'B',
    description: 'A merge can move the receiving ref without creating a merge commit.',
  },
  {
    id: 'merge-commit',
    title: 'Merge commit',
    depth: 'B',
    description: 'A true merge commit joins divergent histories with two parents.',
  },
  {
    id: 'merge-conflict',
    title: 'Merge conflict',
    depth: 'B',
    description: 'Overlapping incompatible changes pause integration for human resolution.',
  },
  {
    id: 'rebase-replay',
    title: 'Rebase replay',
    depth: 'B',
    description: 'Replay changes as replacement commits on a different base.',
  },
  {
    id: 'recovery',
    title: 'Recovery reasoning',
    depth: 'A',
    description: 'Choose recovery by identifying which state layer is wrong.',
  },
  {
    id: 'restore',
    title: 'Restore',
    depth: 'A',
    description: 'Restore working or staged content without moving history.',
  },
  {
    id: 'revert',
    title: 'Revert',
    depth: 'B',
    description: 'Undo a recorded change by creating a new inverse commit.',
  },
  {
    id: 'reset-modes',
    title: 'Reset modes',
    depth: 'B',
    description: 'Move a branch while deliberately choosing what happens to index and working tree.',
  },
  { id: 'stash', title: 'Stash', depth: 'A', description: 'Temporarily shelve uncommitted work and restore it later.' },
  {
    id: 'reflog',
    title: 'Reflog',
    depth: 'B',
    description: 'Local evidence of recent HEAD and branch movement useful for recovery.',
  },
  { id: 'remote', title: 'Remote', depth: 'A', description: 'A named connection to another repository copy.' },
  {
    id: 'remote-tracking',
    title: 'Remote-tracking ref',
    depth: 'B',
    description: 'A local ref recording the last fetched position of a remote branch.',
  },
  {
    id: 'upstream',
    title: 'Upstream relationship',
    depth: 'B',
    description: 'Configuration connecting a local branch to its default remote branch.',
  },
  {
    id: 'fetch',
    title: 'Fetch',
    depth: 'A',
    description: 'Update local knowledge of a remote without integrating into the current branch.',
  },
  {
    id: 'push',
    title: 'Push',
    depth: 'A',
    description: 'Advance a remote branch when local history safely contains its current tip.',
  },
  {
    id: 'pull',
    title: 'Pull',
    depth: 'B',
    description: 'Convenience operation combining fetch with configured integration.',
  },
  { id: 'tag', title: 'Tag', depth: 'B', description: 'A stable name for a particular commit.' },
  {
    id: 'cherry-pick',
    title: 'Cherry-pick',
    depth: 'B',
    description: 'Replay one selected commit change as a new commit.',
  },
  {
    id: 'transfer-practice',
    title: 'Transfer practice',
    depth: 'A',
    description: 'Solve a changed repository goal without copying the worked example.',
  },
  {
    id: 'commit-object',
    title: 'Commit object',
    depth: 'C',
    description: 'Metadata plus parent links and a pointer to a project tree.',
  },
  {
    id: 'tree-object',
    title: 'Tree object',
    depth: 'C',
    description: 'Directory structure that recursively names trees and blob content.',
  },
  {
    id: 'blob-object',
    title: 'Blob object',
    depth: 'C',
    description: 'Content-addressed file data behind a recorded snapshot.',
  },
]

export const CONCEPT_IDS = new Set(CONCEPTS.map((concept) => concept.id))
